"""
Commodity AI Engine - Demand Leakage & Capture Opportunity Detection
INIBSA Smart Demand Signals Platform
"""

from __future__ import annotations

import argparse
import importlib.util
import json
import logging
import pickle
import sys
from dataclasses import asdict, dataclass
from enum import Enum
from pathlib import Path
from typing import Dict, Iterable, List, Optional, Tuple

import numpy as np
import pandas as pd
from sklearn.cluster import KMeans
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import (
    calinski_harabasz_score,
    davies_bouldin_score,
    r2_score,
    silhouette_score,
)
from sklearn.preprocessing import StandardScaler

try:
    import lightgbm as lgb
except ImportError:  # pragma: no cover - fallback is validated at runtime
    lgb = None


BACKEND_ROOT = Path(__file__).resolve().parents[3]
PROJECT_ROOT = BACKEND_ROOT.parent
FEATURE_ENGINEERING_DIR = BACKEND_ROOT / "feature_engineering"
if str(FEATURE_ENGINEERING_DIR) not in sys.path:
    sys.path.insert(0, str(FEATURE_ENGINEERING_DIR))

try:
    from config import FeatureConfig
    from features import (
        build_client_features,
        build_client_product_features,
        build_product_features,
        load_feature_source_frame,
        prepare_feature_source_frame,
    )
except ImportError as exc:  # pragma: no cover - validated at runtime
    raise ImportError(
        "Commodity AI Engine requires backend/feature_engineering to be importable."
    ) from exc


logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


class CustomerCluster(Enum):
    """Customer behavioral segments for commodity products."""

    NULL_OR_MARGINAL = 0
    LOYAL = 1
    PROMISCUOUS = 2


@dataclass
class CommoditySignal:
    """Signal generated by commodity engine for a specific customer/product."""

    customer_id: str
    product_family: str
    signal_type: str = "demand_leakage"
    leakage_score: float = 0.0
    predicted_monthly_consumption: float = 0.0
    observed_monthly_consumption: float = 0.0
    gap_units: float = 0.0
    estimated_lost_revenue: float = 0.0
    customer_cluster: str = ""
    urgency: float = 0.0
    confidence: float = 0.0
    recommended_action: str = ""
    timeline: List[str] | None = None

    def to_dict(self) -> dict:
        return asdict(self)


def _parquet_engine() -> str:
    if importlib.util.find_spec("pyarrow") is not None:
        return "pyarrow"
    if importlib.util.find_spec("fastparquet") is not None:
        return "fastparquet"
    raise RuntimeError(
        "Parquet output requires either 'pyarrow' or 'fastparquet' to be installed."
    )


def _write_parquet(df: pd.DataFrame, output_path: Path) -> Path:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    df.to_parquet(
        output_path,
        index=False,
        compression="snappy",
        engine=_parquet_engine(),
    )
    return output_path


def _write_json(payload: dict, output_path: Path) -> Path:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(
        json.dumps(payload, indent=2, ensure_ascii=True),
        encoding="utf-8",
    )
    return output_path


def _write_pickle(payload: object, output_path: Path) -> Path:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with output_path.open("wb") as handle:
        pickle.dump(payload, handle)
    return output_path


def _read_pickle(path: Path) -> object:
    if not path.exists():
        raise FileNotFoundError(f"Required pickle artifact was not found: {path}")
    with path.open("rb") as handle:
        return pickle.load(handle)


def _read_frame(path: Path) -> pd.DataFrame:
    if not path.exists():
        raise FileNotFoundError(f"Required input was not found: {path}")
    if path.suffix.lower() == ".csv":
        for encoding in ("utf-8-sig", "utf-8", "latin-1"):
            try:
                return pd.read_csv(path, encoding=encoding, low_memory=False)
            except UnicodeDecodeError:
                continue
        raise UnicodeDecodeError("utf-8", b"", 0, 1, f"Could not decode {path}")
    if path.suffix.lower() == ".parquet":
        return pd.read_parquet(path)
    raise ValueError(f"Unsupported file format for {path}")


def _resolve_existing_path(base_dir: Path, candidates: Iterable[str], label: str) -> Path:
    for candidate in candidates:
        candidate_path = base_dir / candidate
        if candidate_path.exists():
            return candidate_path
    raise FileNotFoundError(
        f"Missing required {label} input in {base_dir}. "
        f"Expected one of: {', '.join(candidates)}"
    )


def _normalize_identifier(series: pd.Series) -> pd.Series:
    return series.astype("string").str.strip()


def _normalize_boolean(series: pd.Series) -> pd.Series:
    if pd.api.types.is_bool_dtype(series):
        return series.fillna(False).astype(bool)
    normalized = (
        series.astype("string")
        .str.strip()
        .str.lower()
        .map(
            {
                "true": True,
                "false": False,
                "1": True,
                "0": False,
                "yes": True,
                "no": False,
                "nan": False,
                "<na>": False,
            }
        )
    )
    return normalized.fillna(False).astype(bool)


def _normalize_frame_types(df: pd.DataFrame) -> pd.DataFrame:
    normalized = df.copy()
    for column in ("client_id", "customer_id", "product_id", "product_family", "family", "postal_code", "province", "category", "analytic_block"):
        if column in normalized.columns:
            normalized[column] = _normalize_identifier(normalized[column])
    for column in ("is_active_customer", "is_return", "is_campaign_period", "is_month_end", "is_quarter_end"):
        if column in normalized.columns:
            normalized[column] = _normalize_boolean(normalized[column])
    for column in normalized.columns:
        if column.endswith("_date") or column in {"date", "forecast_date", "snapshot_date"}:
            normalized[column] = pd.to_datetime(normalized[column], errors="coerce")
    return normalized


def _metrics_dir(output_dir: Path) -> Path:
    path = output_dir / "metrics"
    path.mkdir(parents=True, exist_ok=True)
    return path


def _models_dir(output_dir: Path) -> Path:
    path = output_dir / "models"
    path.mkdir(parents=True, exist_ok=True)
    return path


def _compute_regression_metrics(
    actual: pd.Series | np.ndarray,
    predicted: pd.Series | np.ndarray,
    *,
    baseline: pd.Series | np.ndarray | None = None,
) -> dict:
    actual_array = np.asarray(actual, dtype=float)
    predicted_array = np.asarray(predicted, dtype=float)
    residuals = actual_array - predicted_array
    rmse = float(np.sqrt(np.mean(np.square(residuals))))
    mae = float(np.mean(np.abs(residuals)))
    denominator = float(np.sum(np.abs(actual_array))) + 1e-9
    wmape = float(np.sum(np.abs(residuals)) / denominator)
    non_zero_mask = actual_array != 0
    if non_zero_mask.any():
        mape_nonzero = float(
            np.mean(np.abs((actual_array[non_zero_mask] - predicted_array[non_zero_mask]) / actual_array[non_zero_mask]))
        )
    else:
        mape_nonzero = 0.0
    metrics = {
        "rmse": rmse,
        "mae": mae,
        "wmape": wmape,
        "mape_nonzero": mape_nonzero,
        "r2": float(r2_score(actual_array, predicted_array)) if len(actual_array) > 1 else 0.0,
    }
    if baseline is not None:
        baseline_array = np.asarray(baseline, dtype=float)
        baseline_residuals = actual_array - baseline_array
        baseline_rmse = float(np.sqrt(np.mean(np.square(baseline_residuals))))
        baseline_mae = float(np.mean(np.abs(baseline_residuals)))
        baseline_wmape = float(np.sum(np.abs(baseline_residuals)) / denominator)
        metrics.update(
            {
                "baseline_rmse": baseline_rmse,
                "baseline_mae": baseline_mae,
                "baseline_wmape": baseline_wmape,
                "rmse_improvement_vs_baseline": baseline_rmse - rmse,
                "wmape_improvement_vs_baseline": baseline_wmape - wmape,
            }
        )
    return metrics


__all__ = [name for name in globals() if not name.startswith("__")]
