"""
Commodity AI Engine - Demand Leakage & Capture Opportunity Detection
INIBSA Smart Demand Signals Platform
"""

from __future__ import annotations

import argparse
import importlib.util
import json
import logging
import sys
from dataclasses import asdict, dataclass
from enum import Enum
from pathlib import Path
from typing import Dict, Iterable, List, Optional, Tuple

import numpy as np
import pandas as pd
from sklearn.cluster import KMeans
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import (
    calinski_harabasz_score,
    davies_bouldin_score,
    r2_score,
    silhouette_score,
)
from sklearn.preprocessing import StandardScaler

try:
    import lightgbm as lgb
except ImportError:  # pragma: no cover - fallback is validated at runtime
    lgb = None


FEATURE_ENGINEERING_DIR = Path(__file__).resolve().parents[2] / "feature_engineering"
if str(FEATURE_ENGINEERING_DIR) not in sys.path:
    sys.path.insert(0, str(FEATURE_ENGINEERING_DIR))

try:
    from config import FeatureConfig
    from features import (
        build_client_features,
        build_client_product_features,
        build_product_features,
        load_feature_source_frame,
        prepare_feature_source_frame,
    )
except ImportError as exc:  # pragma: no cover - validated at runtime
    raise ImportError(
        "Commodity AI Engine requires backend/feature_engineering to be importable."
    ) from exc


logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


class CustomerCluster(Enum):
    """Customer behavioral segments for commodity products."""

    NULL_OR_MARGINAL = 0
    LOYAL = 1
    PROMISCUOUS = 2


@dataclass
class CommoditySignal:
    """Signal generated by commodity engine for a specific customer/product."""

    customer_id: str
    product_family: str
    signal_type: str = "demand_leakage"
    leakage_score: float = 0.0
    predicted_monthly_consumption: float = 0.0
    observed_monthly_consumption: float = 0.0
    gap_units: float = 0.0
    estimated_lost_revenue: float = 0.0
    customer_cluster: str = ""
    urgency: float = 0.0
    confidence: float = 0.0
    recommended_action: str = ""
    timeline: List[str] | None = None

    def to_dict(self) -> dict:
        return asdict(self)


def _parquet_engine() -> str:
    if importlib.util.find_spec("pyarrow") is not None:
        return "pyarrow"
    if importlib.util.find_spec("fastparquet") is not None:
        return "fastparquet"
    raise RuntimeError(
        "Parquet output requires either 'pyarrow' or 'fastparquet' to be installed."
    )


def _write_parquet(df: pd.DataFrame, output_path: Path) -> Path:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    df.to_parquet(
        output_path,
        index=False,
        compression="snappy",
        engine=_parquet_engine(),
    )
    return output_path


def _write_json(payload: dict, output_path: Path) -> Path:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(
        json.dumps(payload, indent=2, ensure_ascii=True),
        encoding="utf-8",
    )
    return output_path


def _read_frame(path: Path) -> pd.DataFrame:
    if not path.exists():
        raise FileNotFoundError(f"Required input was not found: {path}")
    if path.suffix.lower() == ".csv":
        for encoding in ("utf-8-sig", "utf-8", "latin-1"):
            try:
                return pd.read_csv(path, encoding=encoding, low_memory=False)
            except UnicodeDecodeError:
                continue
        raise UnicodeDecodeError("utf-8", b"", 0, 1, f"Could not decode {path}")
    if path.suffix.lower() == ".parquet":
        return pd.read_parquet(path)
    raise ValueError(f"Unsupported file format for {path}")


def _resolve_existing_path(base_dir: Path, candidates: Iterable[str], label: str) -> Path:
    for candidate in candidates:
        candidate_path = base_dir / candidate
        if candidate_path.exists():
            return candidate_path
    raise FileNotFoundError(
        f"Missing required {label} input in {base_dir}. "
        f"Expected one of: {', '.join(candidates)}"
    )


def _normalize_identifier(series: pd.Series) -> pd.Series:
    return series.astype("string").str.strip()


def _normalize_boolean(series: pd.Series) -> pd.Series:
    if pd.api.types.is_bool_dtype(series):
        return series.fillna(False).astype(bool)
    normalized = (
        series.astype("string")
        .str.strip()
        .str.lower()
        .map(
            {
                "true": True,
                "false": False,
                "1": True,
                "0": False,
                "yes": True,
                "no": False,
                "nan": False,
                "<na>": False,
            }
        )
    )
    return normalized.fillna(False).astype(bool)


def _normalize_frame_types(df: pd.DataFrame) -> pd.DataFrame:
    normalized = df.copy()
    for column in ("client_id", "customer_id", "product_id", "product_family", "family", "postal_code", "province", "category", "analytic_block"):
        if column in normalized.columns:
            normalized[column] = _normalize_identifier(normalized[column])
    for column in ("is_active_customer", "is_return", "is_campaign_period", "is_month_end", "is_quarter_end"):
        if column in normalized.columns:
            normalized[column] = _normalize_boolean(normalized[column])
    for column in normalized.columns:
        if column.endswith("_date") or column in {"date", "forecast_date", "snapshot_date"}:
            normalized[column] = pd.to_datetime(normalized[column], errors="coerce")
    return normalized


def _metrics_dir(output_dir: Path) -> Path:
    path = output_dir / "metrics"
    path.mkdir(parents=True, exist_ok=True)
    return path


def _compute_regression_metrics(
    actual: pd.Series | np.ndarray,
    predicted: pd.Series | np.ndarray,
    *,
    baseline: pd.Series | np.ndarray | None = None,
) -> dict:
    actual_array = np.asarray(actual, dtype=float)
    predicted_array = np.asarray(predicted, dtype=float)
    residuals = actual_array - predicted_array
    rmse = float(np.sqrt(np.mean(np.square(residuals))))
    mae = float(np.mean(np.abs(residuals)))
    denominator = float(np.sum(np.abs(actual_array))) + 1e-9
    wmape = float(np.sum(np.abs(residuals)) / denominator)
    non_zero_mask = actual_array != 0
    if non_zero_mask.any():
        mape_nonzero = float(
            np.mean(np.abs((actual_array[non_zero_mask] - predicted_array[non_zero_mask]) / actual_array[non_zero_mask]))
        )
    else:
        mape_nonzero = 0.0
    metrics = {
        "rmse": rmse,
        "mae": mae,
        "wmape": wmape,
        "mape_nonzero": mape_nonzero,
        "r2": float(r2_score(actual_array, predicted_array)) if len(actual_array) > 1 else 0.0,
    }
    if baseline is not None:
        baseline_array = np.asarray(baseline, dtype=float)
        baseline_residuals = actual_array - baseline_array
        baseline_rmse = float(np.sqrt(np.mean(np.square(baseline_residuals))))
        baseline_mae = float(np.mean(np.abs(baseline_residuals)))
        baseline_wmape = float(np.sum(np.abs(baseline_residuals)) / denominator)
        metrics.update(
            {
                "baseline_rmse": baseline_rmse,
                "baseline_mae": baseline_mae,
                "baseline_wmape": baseline_wmape,
                "rmse_improvement_vs_baseline": baseline_rmse - rmse,
                "wmape_improvement_vs_baseline": baseline_wmape - wmape,
            }
        )
    return metrics


class CommodityCustomerCluster:
    """
    KMeans clustering for commodity product customers.
    Segments customers by purchasing behavior using current client feature tables.
    """

    _cluster_feature_columns: Tuple[str, ...] = (
        "customer_total_revenue",
        "customer_total_orders",
        "customer_avg_ticket",
        "customer_frequency",
        "customer_frequency_log1p",
        "days_since_last_order",
        "is_active_customer",
        "return_rate_30d",
        "campaign_lift",
        "coefficient_variation_30d",
    )
    _excel_required_columns: Tuple[str, ...] = (
        "customer_total_revenue",
        "customer_total_orders",
        "customer_avg_ticket",
        "customer_frequency",
        "days_since_last_order",
        "return_rate_30d",
        "campaign_lift",
        "coefficient_variation_30d",
    )
    _zero_fill_columns: Tuple[str, ...] = (
        "return_rate_30d",
        "campaign_lift",
    )
    _customer_id_columns: Tuple[str, ...] = (
        "client_id",
        "customer_id",
    )
    _client_table_candidates: Tuple[str, ...] = (
        "clients.csv",
        "client_features.csv",
        "client_features.parquet",
        "clients.parquet",
    )

    def __init__(self, n_clusters: int = 3, random_state: int = 42):
        self.n_clusters = n_clusters
        self.random_state = random_state
        self.kmeans = KMeans(n_clusters=n_clusters, random_state=random_state)
        self.scaler = StandardScaler()

    def load_inputs(self, features_dir: Path) -> pd.DataFrame:
        """Load client-level feature tables for clustering."""
        features_dir = Path(features_dir)
        if not features_dir.exists():
            raise FileNotFoundError(f"Features directory not found: {features_dir}")

        client_path = _resolve_existing_path(
            features_dir,
            self._client_table_candidates,
            "client table",
        )
        logger.info("Loading client features from %s", client_path)
        df = _normalize_frame_types(_read_frame(client_path))
        if df.empty:
            raise ValueError(f"{client_path.name} is empty")
        logger.info("Loaded %s rows with %s columns", len(df), len(df.columns))
        return df

    def validate_schema(self, df: pd.DataFrame) -> None:
        """Validate the input schema against the Excel definition plus real model extras."""
        if df.empty:
            raise ValueError("Input features DataFrame is empty")

        schema_columns = self._load_schema_columns()
        missing_in_schema = sorted(set(self._excel_required_columns) - set(schema_columns))
        if missing_in_schema:
            missing = ", ".join(missing_in_schema)
            raise ValueError(f"Excel schema missing required clustering columns: {missing}")

        missing_in_df = sorted(set(self._cluster_feature_columns) - set(df.columns))
        if missing_in_df:
            missing = ", ".join(missing_in_df)
            raise ValueError(f"Input data missing required clustering columns: {missing}")

        id_column = self._resolve_customer_id_column(df.columns)
        if id_column is None:
            raise ValueError("Input data must include client_id or customer_id")

    def prepare_matrix(self, df: pd.DataFrame) -> pd.DataFrame:
        """Prepare standardized numeric feature matrix for clustering."""
        self.validate_schema(df)
        features = self._coerce_and_fill(df.loc[:, self._cluster_feature_columns])
        if hasattr(self.scaler, "mean_"):
            scaled = self.scaler.transform(features)
        else:
            scaled = self.scaler.fit_transform(features)
        return pd.DataFrame(scaled, columns=self._cluster_feature_columns, index=df.index)

    def fit(self, X: pd.DataFrame, raw_df: Optional[pd.DataFrame] = None) -> None:
        """Fit KMeans clustering on a prepared feature matrix."""
        if X is None or len(X) == 0:
            raise ValueError("Cannot fit clustering on empty feature matrix")
        self.kmeans.fit(X)
        counts = np.bincount(self.kmeans.labels_, minlength=self.n_clusters)
        if (counts == 0).any():
            raise ValueError("At least one cluster has zero customers; adjust n_clusters")
        if raw_df is not None:
            self._remap_cluster_order(raw_df, self.kmeans.labels_)

    def predict(self, X: pd.DataFrame) -> np.ndarray:
        """Predict cluster assignments for a prepared feature matrix."""
        if not hasattr(self.kmeans, "cluster_centers_"):
            raise ValueError("KMeans model is not fitted yet")
        return self.kmeans.predict(X)

    def build_cluster_profiles(self, raw_df: pd.DataFrame, labels: np.ndarray) -> pd.DataFrame:
        """Build mean profiles and counts for each cluster."""
        if raw_df.empty:
            raise ValueError("Cannot build profiles from empty data")
        self.validate_schema(raw_df)
        profiles_source = self._coerce_and_fill(raw_df.loc[:, self._cluster_feature_columns])
        profiles_source["cluster_id"] = labels
        means = profiles_source.groupby("cluster_id")[list(self._cluster_feature_columns)].mean()
        counts = profiles_source.groupby("cluster_id").size().rename("count")
        profiles = means.join(counts).reset_index().sort_values("cluster_id").reset_index(drop=True)
        profiles["cluster_name"] = profiles["cluster_id"].map(self.get_cluster_name)
        if (profiles["count"] == 0).any():
            raise ValueError("Cluster profiles contain empty clusters")
        return profiles

    def compute_metrics(self, X: pd.DataFrame, labels: np.ndarray) -> dict:
        counts = pd.Series(labels).value_counts().sort_index()
        total = int(counts.sum()) if len(counts) else 0
        return {
            "n_clusters": int(self.n_clusters),
            "rows": int(len(X)),
            "inertia": float(self.kmeans.inertia_),
            "silhouette_score": float(silhouette_score(X, labels)) if len(counts) > 1 else 0.0,
            "davies_bouldin_score": float(davies_bouldin_score(X, labels)) if len(counts) > 1 else 0.0,
            "calinski_harabasz_score": float(calinski_harabasz_score(X, labels)) if len(counts) > 1 else 0.0,
            "cluster_counts": {str(int(cluster_id)): int(count) for cluster_id, count in counts.items()},
            "cluster_labels": {str(int(cluster_id)): self.get_cluster_name(int(cluster_id)) for cluster_id in counts.index},
            "min_cluster_share": float(counts.min() / total) if total else 0.0,
        }

    def save_outputs(
        self,
        output_dir: Path,
        customer_ids: pd.Series,
        labels: np.ndarray,
        profiles: pd.DataFrame,
    ) -> Tuple[Path, Path]:
        """Persist cluster assignments and profiles to parquet files."""
        output_dir.mkdir(parents=True, exist_ok=True)
        assignments = pd.DataFrame(
            {
                "customer_id": customer_ids.astype("string"),
                "cluster_id": labels.astype(int),
            }
        )
        assignments_path = _write_parquet(assignments, output_dir / "cluster_assignments.parquet")
        profiles_path = _write_parquet(profiles, output_dir / "cluster_profiles.parquet")
        logger.info("Saved cluster assignments to %s", assignments_path)
        logger.info("Saved cluster profiles to %s", profiles_path)
        return assignments_path, profiles_path

    def get_cluster_name(self, cluster_id: int) -> str:
        if self.n_clusters == 3:
            try:
                return CustomerCluster(cluster_id).name.lower()
            except ValueError:
                return f"cluster_{cluster_id}"
        return f"cluster_{cluster_id}"

    @staticmethod
    def _schema_path() -> Path:
        return Path(__file__).resolve().parents[2] / "data_processing" / "inibsa_feature_tables.xlsx"

    def _load_schema_columns(self) -> List[str]:
        schema_path = self._schema_path()
        if not schema_path.exists():
            raise FileNotFoundError(f"Schema file not found: {schema_path}")
        try:
            schema_df = pd.read_excel(schema_path, sheet_name="clients")
        except ImportError as exc:
            raise ImportError(
                "Reading inibsa_feature_tables.xlsx requires 'openpyxl' to be installed"
            ) from exc
        except ValueError as exc:
            raise ValueError("Sheet 'clients' not found in schema workbook") from exc
        if "Column" not in schema_df.columns:
            raise ValueError("Schema sheet must include a 'Column' header")
        return schema_df["Column"].dropna().astype(str).str.strip().tolist()

    def _coerce_and_fill(self, features: pd.DataFrame) -> pd.DataFrame:
        filled = features.copy()
        for column in self._cluster_feature_columns:
            if column == "is_active_customer":
                filled[column] = _normalize_boolean(filled[column]).astype(int)
            else:
                filled[column] = pd.to_numeric(filled[column], errors="coerce")
        for column in self._zero_fill_columns:
            filled[column] = filled[column].fillna(0.0)
        for column in self._cluster_feature_columns:
            if column in self._zero_fill_columns:
                continue
            median_value = filled[column].median()
            if pd.isna(median_value):
                median_value = 0.0
            filled[column] = filled[column].fillna(median_value)
        return filled.fillna(0.0)

    def _resolve_customer_id_column(self, columns: Iterable[str]) -> Optional[str]:
        column_set = set(columns)
        for candidate in self._customer_id_columns:
            if candidate in column_set:
                return candidate
        return None

    def _remap_cluster_order(self, raw_df: pd.DataFrame, labels: np.ndarray) -> None:
        profiles_source = self._coerce_and_fill(raw_df.loc[:, self._cluster_feature_columns])
        profiles_source["cluster_id"] = labels
        ordering = (
            profiles_source.groupby("cluster_id")
            .agg(
                revenue=("customer_total_revenue", "mean"),
                frequency=("customer_frequency", "mean"),
                recency=("days_since_last_order", "mean"),
                active_ratio=("is_active_customer", "mean"),
                return_rate_30d=("return_rate_30d", "mean"),
                coefficient_variation_30d=("coefficient_variation_30d", "mean"),
            )
            .sort_values(
                ["revenue", "frequency", "recency", "active_ratio"],
                ascending=[False, False, True, False],
            )
        )
        if self.n_clusters == 3:
            ordered_cluster_ids = self._business_cluster_order(ordering)
        else:
            ordered_cluster_ids = ordering.index.tolist()
        mapping = {old_id: new_id for new_id, old_id in enumerate(ordered_cluster_ids)}
        reordered_centers = self.kmeans.cluster_centers_[ordered_cluster_ids]
        self.kmeans.cluster_centers_ = reordered_centers
        self.kmeans.labels_ = np.asarray([mapping[label] for label in labels], dtype=int)

    def _business_cluster_order(self, ordering: pd.DataFrame) -> List[int]:
        profiles = ordering.copy()
        revenue = self._scale_series(profiles["revenue"], high_is_good=True)
        frequency = self._scale_series(profiles["frequency"], high_is_good=True)
        recency = self._scale_series(profiles["recency"], high_is_good=True)
        active_ratio = self._scale_series(profiles["active_ratio"], high_is_good=True)

        profiles["loyal_score"] = revenue + frequency + active_ratio + (1 - recency)
        profiles["marginal_score"] = recency + (1 - active_ratio) + (1 - revenue) + (1 - frequency)
        profiles["promiscuous_score"] = (
            self._scale_series(profiles["frequency"], high_is_good=True) * 0.5
            + self._scale_series(profiles["active_ratio"], high_is_good=True) * 0.25
            + self._scale_series(profiles["recency"], high_is_good=False) * 0.25
        )
        if "return_rate_30d" in profiles.columns:
            profiles["promiscuous_score"] = profiles["promiscuous_score"] + self._scale_series(
                profiles["return_rate_30d"], high_is_good=True
            )
        if "coefficient_variation_30d" in profiles.columns:
            profiles["promiscuous_score"] = profiles["promiscuous_score"] + self._scale_series(
                profiles["coefficient_variation_30d"], high_is_good=True
            )

        available_ids = set(profiles.index.tolist())
        marginal_id = int(profiles["marginal_score"].idxmax())
        available_ids.remove(marginal_id)
        loyal_candidates = profiles.loc[list(available_ids)]
        loyal_id = int(loyal_candidates["loyal_score"].idxmax())
        available_ids.remove(loyal_id)
        promiscuous_id = int(next(iter(available_ids)))
        return [marginal_id, loyal_id, promiscuous_id]

    @staticmethod
    def _scale_series(series: pd.Series, *, high_is_good: bool) -> pd.Series:
        numeric = pd.to_numeric(series, errors="coerce").fillna(0.0).astype(float)
        if numeric.nunique() <= 1:
            scaled = pd.Series(0.0, index=numeric.index, dtype=float)
        else:
            scaled = (numeric - numeric.min()) / (numeric.max() - numeric.min())
        return scaled if high_is_good else 1.0 - scaled


class DemandForecaster:
    """
    LightGBM-based demand forecasting for commodity products.
    Predicts next 30-day expected sales using a temporal training panel.
    """

    _client_sheet = "clients"
    _product_sheet = "products"
    _client_product_sheet = "client_product_features"
    _cluster_file_name = "cluster_assignments.parquet"
    _target_candidates: Tuple[str, ...] = (
        "target_30d_sales",
        "next_30d_sales",
        "future_30d_sales",
        "expected_30d_sales",
    )
    _time_columns: Tuple[str, ...] = (
        "snapshot_date",
        "feature_date",
        "as_of_date",
        "forecast_date",
        "date",
        "month",
    )
    _customer_id_candidates: Tuple[str, ...] = (
        "customer_id",
        "client_id",
    )
    _product_id_candidates: Tuple[str, ...] = (
        "product_id",
        "product_family",
        "family",
    )
    _priority_client_product_columns: Tuple[str, ...] = (
        "rolling_sales_30d",
        "sales_growth_30d",
        "days_since_last_product_order",
        "client_product_frequency",
        "client_product_avg_ticket",
        "client_product_return_rate",
        "campaign_lift_product",
        "client_product_total_revenue",
        "client_product_total_orders",
    )
    _priority_product_columns: Tuple[str, ...] = (
        "product_growth_30d",
        "product_frequency",
        "product_return_rate",
    )
    _priority_client_columns: Tuple[str, ...] = (
        "customer_frequency",
        "customer_frequency_log1p",
        "campaign_lift",
        "is_active_customer",
    )
    _client_table_candidates: Tuple[str, ...] = (
        "clients.csv",
        "client_features.csv",
        "client_features.parquet",
        "clients.parquet",
    )
    _product_table_candidates: Tuple[str, ...] = (
        "products.csv",
        "product_features.csv",
        "product_features.parquet",
        "products.parquet",
    )
    _client_product_table_candidates: Tuple[str, ...] = (
        "client_product_features.csv",
        "client_product_features.parquet",
    )

    def __init__(self, model_params: Optional[Dict] = None):
        self.model = None
        self.model_backend = "lightgbm" if lgb is not None else "sklearn"
        self.feature_names: List[str] = []
        self.raw_feature_columns: List[str] = []
        self.feature_dtypes: Dict[str, str] = {}
        self.categorical_levels: Dict[str, List[str]] = {}
        self.numeric_fill_values: Dict[str, float] = {}
        self.validation_rmse_: Optional[float] = None
        self.validation_mae_: Optional[float] = None
        self.base_confidence_: float = 0.5
        self.train_feature_means_: Optional[pd.Series] = None
        self.train_feature_stds_: Optional[pd.Series] = None
        self.training_order_: Optional[pd.Series] = None
        self.target_column: Optional[str] = None
        self.product_key_column: Optional[str] = None
        self.customer_key_column: str = "customer_id"
        self.model_params = model_params or {
            "learning_rate": 0.05,
            "num_leaves": 31,
            "max_depth": 5,
            "objective": "regression",
            "metric": "rmse",
            "verbosity": -1,
            "seed": 42,
        }

    def load_inputs(self, features_dir: Path, commodity_output_dir: Path) -> pd.DataFrame:
        """Load and merge latest feature tables with cluster assignments."""
        features_dir = Path(features_dir)
        commodity_output_dir = Path(commodity_output_dir)
        if not features_dir.exists():
            raise FileNotFoundError(f"Features directory not found: {features_dir}")
        if not commodity_output_dir.exists():
            raise FileNotFoundError(f"Commodity output directory not found: {commodity_output_dir}")

        client_product_path = _resolve_existing_path(
            features_dir,
            self._client_product_table_candidates,
            "client-product table",
        )
        product_path = _resolve_existing_path(
            features_dir,
            self._product_table_candidates,
            "product table",
        )
        client_path = _resolve_existing_path(
            features_dir,
            self._client_table_candidates,
            "client table",
        )
        cluster_path = commodity_output_dir / self._cluster_file_name
        if not cluster_path.exists():
            raise FileNotFoundError(f"Missing cluster assignments file: {cluster_path}")

        logger.info("Loading forecast inputs from %s", features_dir)
        client_product_df = _read_frame(client_product_path)
        product_df = _read_frame(product_path)
        client_df = _read_frame(client_path)
        cluster_df = _read_frame(cluster_path)
        return self.merge_feature_tables(
            client_product_df,
            product_df,
            client_df,
            cluster_df,
            source_names={
                "client_product": client_product_path.name,
                "product": product_path.name,
                "client": client_path.name,
            },
            require_target=False,
        )

    def merge_feature_tables(
        self,
        client_product_df: pd.DataFrame,
        product_df: pd.DataFrame,
        client_df: pd.DataFrame,
        cluster_df: pd.DataFrame,
        *,
        source_names: Optional[dict] = None,
        require_target: bool = False,
    ) -> pd.DataFrame:
        """Canonicalize, validate, and merge feature tables."""
        source_names = source_names or {
            "client_product": "client_product_features",
            "product": "products",
            "client": "clients",
        }
        schema_contracts = self._load_schema_contracts()

        client_product_df = self._canonicalize_client_product_df(client_product_df)
        product_df = self._canonicalize_product_df(product_df)
        client_df = self._canonicalize_client_df(client_df)
        cluster_df = self._canonicalize_cluster_df(cluster_df)

        self._validate_input_table(
            client_product_df,
            schema_contracts[self._client_product_sheet],
            source_names["client_product"],
            self._priority_client_product_columns,
            ("customer_id", self._resolved_product_key(client_product_df)),
        )
        self._validate_input_table(
            product_df,
            schema_contracts[self._product_sheet],
            source_names["product"],
            self._priority_product_columns,
            (self._resolved_product_key(product_df),),
        )
        self._validate_input_table(
            client_df,
            schema_contracts[self._client_sheet],
            source_names["client"],
            self._priority_client_columns,
            ("customer_id",),
        )
        self._validate_cluster_assignments(cluster_df)

        merged = client_product_df.merge(
            client_df,
            how="left",
            on="customer_id",
            suffixes=("", "_client"),
            validate="many_to_one",
        )
        product_key = self._resolved_product_key(client_product_df)
        merged = merged.merge(
            product_df,
            how="left",
            on=product_key,
            suffixes=("", "_product"),
            validate="many_to_one",
        )
        merged = merged.merge(
            cluster_df[["customer_id", "cluster_id"]],
            how="left",
            on="customer_id",
            validate="many_to_one",
        )

        self.product_key_column = product_key
        merged = _normalize_frame_types(merged)
        self.validate_schema(merged, require_target=require_target)
        return merged

    def validate_schema(self, df: pd.DataFrame, *, require_target: bool = True) -> None:
        """Validate merged forecast schema before training or inference."""
        if df.empty:
            raise ValueError("Forecast input DataFrame is empty")

        required_columns = {
            "customer_id",
            "cluster_id",
            self._resolved_product_key(df),
        }
        for column_group in (
            self._priority_client_product_columns,
            self._priority_product_columns,
            self._priority_client_columns,
        ):
            required_columns.update(column_group)

        missing_columns = sorted(column for column in required_columns if column not in df.columns)
        if missing_columns:
            raise ValueError(
                "Merged forecast frame is missing required columns: "
                + ", ".join(missing_columns)
            )

        if require_target:
            self.target_column = None
            for column in self._target_candidates:
                if column in df.columns:
                    self.target_column = column
                    break
            if self.target_column is None:
                raise ValueError(
                    "Forecast target column not found. Expected one of: "
                    + ", ".join(self._target_candidates)
                )

    def build_training_frame(self, df: pd.DataFrame) -> Tuple[pd.DataFrame, pd.Series]:
        """Prepare the model feature matrix and supervised target."""
        self.validate_schema(df, require_target=True)
        assert self.target_column is not None
        target = pd.to_numeric(df[self.target_column], errors="coerce")
        if target.isna().all():
            raise ValueError(f"Target column {self.target_column} contains only NaN values")

        model_df = self._build_raw_feature_frame(df)
        valid_mask = target.notna()
        model_df = model_df.loc[valid_mask].reset_index(drop=True)
        target = target.loc[valid_mask].clip(lower=0).reset_index(drop=True)

        self.training_order_ = self._build_time_order(model_df)
        X = self._prepare_model_frame(model_df, fit=True)
        self.raw_feature_columns = model_df.columns.tolist()
        self.feature_names = X.columns.tolist()
        return X, target

    def build_prediction_frame(self, df: pd.DataFrame) -> pd.DataFrame:
        """Select raw model columns for inference after training."""
        if not self.raw_feature_columns:
            raise ValueError("Model feature columns are not initialized")
        self.validate_schema(df, require_target=False)
        frame = df.copy()
        for column in self.raw_feature_columns:
            if column not in frame.columns:
                frame[column] = pd.NA
        return frame.loc[:, self.raw_feature_columns].copy()

    def train(self, X: pd.DataFrame, y: pd.Series) -> None:
        """Train the demand forecasting model using a time-aware split."""
        if X.empty or y.empty:
            raise ValueError("Cannot train forecast model on empty data")

        if self.training_order_ is not None and len(self.training_order_) == len(X):
            order = self.training_order_
        else:
            order = self._build_time_order(X)
        train_idx, val_idx = self._time_aware_split_indices(order, len(X))

        X_train = X.iloc[train_idx].reset_index(drop=True)
        y_train = y.iloc[train_idx].reset_index(drop=True)
        X_val = X.iloc[val_idx].reset_index(drop=True)
        y_val = y.iloc[val_idx].reset_index(drop=True)

        self.train_feature_means_ = X_train.mean()
        self.train_feature_stds_ = X_train.std(ddof=0).replace(0, 1).fillna(1)

        if self.model_backend == "lightgbm":
            train_data = lgb.Dataset(X_train, label=y_train, feature_name=self.feature_names)
            valid_sets = [train_data]
            valid_names = ["train"]
            callbacks = []
            if not X_val.empty:
                valid_data = lgb.Dataset(
                    X_val,
                    label=y_val,
                    feature_name=self.feature_names,
                    reference=train_data,
                )
                valid_sets.append(valid_data)
                valid_names.append("valid")
                callbacks.append(lgb.early_stopping(20, verbose=False))
            self.model = lgb.train(
                self.model_params,
                train_data,
                num_boost_round=200,
                valid_sets=valid_sets,
                valid_names=valid_names,
                callbacks=callbacks,
            )
        else:
            self.model = RandomForestRegressor(
                n_estimators=300,
                max_depth=8,
                min_samples_leaf=2,
                random_state=42,
                n_jobs=-1,
            )
            self.model.fit(X_train, y_train)

        eval_features = X_val if not X_val.empty else X_train
        eval_target = y_val if not y_val.empty else y_train
        eval_pred = np.clip(self.predict(eval_features), a_min=0, a_max=None)
        residuals = eval_target.to_numpy(dtype=float) - eval_pred
        self.validation_rmse_ = float(np.sqrt(np.mean(np.square(residuals))))
        self.validation_mae_ = float(np.mean(np.abs(residuals)))
        denominator = float(np.mean(np.abs(eval_target.to_numpy(dtype=float)))) + 1e-6
        relative_error = min(self.validation_mae_ / denominator, 1.0)
        self.base_confidence_ = float(np.clip(1.0 - relative_error, 0.05, 0.95))

    def predict(self, X: pd.DataFrame) -> np.ndarray:
        """Predict expected consumption."""
        if self.model is None:
            raise ValueError("Model not trained yet")
        transformed = self._prepare_model_frame(X, fit=False)
        predictions = self.model.predict(transformed)
        return np.clip(np.asarray(predictions, dtype=float), a_min=0, a_max=None)

    def estimate_confidence(self, X: pd.DataFrame, y_pred: np.ndarray) -> np.ndarray:
        """Estimate per-row forecast confidence in the [0, 1] range."""
        if self.train_feature_means_ is None or self.train_feature_stds_ is None:
            raise ValueError("Forecast model must be trained before estimating confidence")
        transformed = self._prepare_model_frame(X, fit=False)
        aligned_means = self.train_feature_means_.reindex(transformed.columns).fillna(0)
        aligned_stds = self.train_feature_stds_.reindex(transformed.columns).fillna(1)
        z_scores = ((transformed - aligned_means) / aligned_stds).abs().replace([np.inf, -np.inf], 0)
        drift_penalty = np.tanh(z_scores.mean(axis=1) / 3.0)

        scale = (
            self.validation_rmse_
            if self.validation_rmse_ is not None and self.validation_rmse_ > 0
            else max(float(np.nanmean(np.abs(y_pred))), 1.0)
        )
        uncertainty = np.clip(np.abs(y_pred) / (np.abs(y_pred) + scale), 0, 1)
        confidence = self.base_confidence_ * (1 - 0.5 * drift_penalty) * (0.6 + 0.4 * uncertainty)
        confidence = np.nan_to_num(confidence.to_numpy(dtype=float), nan=self.base_confidence_)
        return np.clip(confidence, 0, 1)

    def save_outputs(
        self,
        output_dir: Path,
        base_df: pd.DataFrame,
        y_pred: np.ndarray,
        confidence: np.ndarray,
    ) -> Path:
        """Persist the consumption forecast parquet output."""
        output_dir = Path(output_dir)
        output_dir.mkdir(parents=True, exist_ok=True)
        product_key = self._resolved_product_key(base_df)
        export_df = pd.DataFrame(
            {
                "customer_id": base_df["customer_id"].astype("string"),
                product_key: base_df[product_key].astype("string"),
                "predicted_30d_sales": np.clip(np.asarray(y_pred, dtype=float), 0, None),
                "forecast_confidence": np.clip(np.asarray(confidence, dtype=float), 0, 1),
                "forecast_date": self._build_forecast_dates(base_df),
            }
        )
        if export_df.isna().any().any():
            missing_columns = export_df.columns[export_df.isna().any()].tolist()
            raise ValueError("Forecast output contains NaN values in columns: " + ", ".join(missing_columns))
        output_path = output_dir / "consumption_forecast.parquet"
        _write_parquet(export_df, output_path)
        logger.info("Saved consumption forecast to %s", output_path)
        return output_path

    def get_feature_importance(self) -> Dict[str, float]:
        if self.model is None:
            return {}
        if self.model_backend == "lightgbm":
            importance = self.model.feature_importance()
        else:
            importance = getattr(self.model, "feature_importances_", np.zeros(len(self.feature_names)))
        return {name: float(imp) for name, imp in zip(self.feature_names, importance)}

    @staticmethod
    def _schema_path() -> Path:
        return Path(__file__).resolve().parents[2] / "data_processing" / "inibsa_feature_tables.xlsx"

    def _load_schema_contracts(self) -> Dict[str, List[str]]:
        schema_path = self._schema_path()
        if not schema_path.exists():
            raise FileNotFoundError(f"Schema file not found: {schema_path}")
        try:
            workbook = pd.ExcelFile(schema_path)
        except ImportError as exc:
            raise ImportError(
                "Reading inibsa_feature_tables.xlsx requires 'openpyxl' to be installed"
            ) from exc
        contracts = {}
        for sheet_name in (
            self._client_sheet,
            self._product_sheet,
            self._client_product_sheet,
        ):
            if sheet_name not in workbook.sheet_names:
                raise ValueError(f"Sheet '{sheet_name}' not found in schema workbook")
            sheet_df = pd.read_excel(schema_path, sheet_name=sheet_name)
            if "Column" not in sheet_df.columns:
                raise ValueError(f"Schema sheet '{sheet_name}' must include a 'Column' header")
            contracts[sheet_name] = sheet_df["Column"].dropna().astype(str).str.strip().tolist()
        return contracts

    def _validate_input_table(
        self,
        df: pd.DataFrame,
        schema_columns: List[str],
        file_name: str,
        priority_columns: Iterable[str],
        identifier_columns: Iterable[str],
    ) -> None:
        if df.empty:
            raise ValueError(f"{file_name} is empty")
        required_columns = self._normalize_expected_columns(schema_columns)
        required_columns.update(priority_columns)
        required_columns.update(identifier_columns)
        missing_columns = sorted(column for column in required_columns if column not in df.columns)
        if missing_columns:
            raise ValueError(
                f"{file_name} is missing required columns from Excel contract: "
                + ", ".join(missing_columns)
            )

    def _validate_cluster_assignments(self, df: pd.DataFrame) -> None:
        required_columns = {"customer_id", "cluster_id"}
        missing_columns = sorted(required_columns - set(df.columns))
        if missing_columns:
            raise ValueError(
                "cluster_assignments.parquet is missing required columns: "
                + ", ".join(missing_columns)
            )
        if df["cluster_id"].isna().any():
            raise ValueError("cluster_assignments.parquet contains NaN cluster_id values")

    def _canonicalize_client_product_df(self, df: pd.DataFrame) -> pd.DataFrame:
        renamed = _normalize_frame_types(df)
        customer_column = self._find_first_column(renamed.columns, self._customer_id_candidates)
        if customer_column is None:
            raise ValueError("client_product_features must include client_id or customer_id")
        renamed = renamed.rename(columns={customer_column: "customer_id"})
        if "family" in renamed.columns and "product_family" not in renamed.columns:
            renamed = renamed.rename(columns={"family": "product_family"})
        if "client_product_total_orders" not in renamed.columns:
            total_orders_candidates = (
                "client_product_total_units",
                "client_product_orders",
                "client_product_total_transactions",
            )
            fallback = self._find_first_column(renamed.columns, total_orders_candidates)
            if fallback is not None:
                renamed = renamed.rename(columns={fallback: "client_product_total_orders"})
        return renamed

    def _canonicalize_product_df(self, df: pd.DataFrame) -> pd.DataFrame:
        renamed = _normalize_frame_types(df)
        if "family" in renamed.columns and "product_family" not in renamed.columns:
            renamed = renamed.rename(columns={"family": "product_family"})
        return renamed

    def _canonicalize_client_df(self, df: pd.DataFrame) -> pd.DataFrame:
        renamed = _normalize_frame_types(df)
        customer_column = self._find_first_column(renamed.columns, self._customer_id_candidates)
        if customer_column is None:
            raise ValueError("client features must include client_id or customer_id")
        return renamed.rename(columns={customer_column: "customer_id"})

    def _canonicalize_cluster_df(self, df: pd.DataFrame) -> pd.DataFrame:
        renamed = _normalize_frame_types(df)
        customer_column = self._find_first_column(renamed.columns, self._customer_id_candidates)
        if customer_column is None:
            raise ValueError("cluster_assignments.parquet must include client_id or customer_id")
        renamed = renamed.rename(columns={customer_column: "customer_id"})
        renamed["cluster_id"] = pd.to_numeric(renamed["cluster_id"], errors="coerce")
        return renamed

    @staticmethod
    def _normalize_expected_columns(columns: Iterable[str]) -> set[str]:
        normalized = set()
        for column in columns:
            if column == "client_id":
                normalized.add("customer_id")
            elif column == "family":
                normalized.add("product_family")
            else:
                normalized.add(column)
        return normalized

    @staticmethod
    def _find_first_column(columns: Iterable[str], candidates: Iterable[str]) -> Optional[str]:
        column_set = set(columns)
        for candidate in candidates:
            if candidate in column_set:
                return candidate
        return None

    def _resolved_product_key(self, df: pd.DataFrame) -> str:
        product_key = self._find_first_column(df.columns, self._product_id_candidates)
        if product_key is None:
            raise ValueError("Forecast inputs must include product_id or product_family/family")
        return product_key

    def _build_raw_feature_frame(self, df: pd.DataFrame) -> pd.DataFrame:
        excluded_columns = {
            "customer_id",
            "cluster_id",
            "predicted_30d_sales",
            "forecast_confidence",
            "baseline_30d_sales",
        }
        if self.target_column is not None:
            excluded_columns.add(self.target_column)

        feature_columns = [
            column
            for column in df.columns
            if column not in excluded_columns and not column.endswith("_id")
        ]
        feature_columns.append("cluster_id")
        feature_columns = list(dict.fromkeys(feature_columns))

        missing_for_training = [column for column in feature_columns if column not in df.columns]
        if missing_for_training:
            raise ValueError("Missing expected training columns: " + ", ".join(missing_for_training))
        return df.loc[:, feature_columns].copy()

    def _prepare_model_frame(self, df: pd.DataFrame, fit: bool) -> pd.DataFrame:
        frame = _normalize_frame_types(df)
        transformed_columns: Dict[str, pd.Series] = {}
        for column in frame.columns:
            if fit:
                inferred_numeric = pd.to_numeric(frame[column], errors="coerce")
                numeric_ratio = inferred_numeric.notna().mean()
                if numeric_ratio >= 0.8:
                    fill_value = inferred_numeric.median()
                    if pd.isna(fill_value):
                        fill_value = 0.0
                    self.feature_dtypes[column] = "numeric"
                    self.numeric_fill_values[column] = float(fill_value)
                    transformed_columns[column] = inferred_numeric.fillna(fill_value).astype(float)
                else:
                    values = frame[column].astype("string").fillna("__missing__")
                    categories = pd.Index(values.unique()).astype(str).tolist()
                    self.feature_dtypes[column] = "categorical"
                    self.categorical_levels[column] = categories
                    codes = pd.Categorical(values, categories=categories).codes.astype(float)
                    transformed_columns[column] = pd.Series(codes, index=frame.index)
            else:
                dtype = self.feature_dtypes.get(column)
                if dtype == "numeric":
                    numeric_series = pd.to_numeric(frame[column], errors="coerce")
                    fill_value = self.numeric_fill_values.get(column, 0.0)
                    transformed_columns[column] = numeric_series.fillna(fill_value).astype(float)
                elif dtype == "categorical":
                    categories = list(self.categorical_levels.get(column, []))
                    if "__unseen__" not in categories:
                        categories.append("__unseen__")
                    values = frame[column].astype("string").fillna("__missing__")
                    values = values.where(values.isin(categories), "__unseen__")
                    codes = pd.Categorical(values, categories=categories).codes.astype(float)
                    transformed_columns[column] = pd.Series(codes, index=frame.index)
                else:
                    transformed_columns[column] = pd.Series(0.0, index=frame.index)
        transformed = pd.DataFrame(transformed_columns, index=frame.index)
        transformed = transformed.replace([np.inf, -np.inf], np.nan).fillna(0.0)
        if not fit:
            for missing_column in self.feature_names:
                if missing_column not in transformed.columns:
                    transformed[missing_column] = 0.0
            transformed = transformed.loc[:, self.feature_names]
        return transformed

    def _build_time_order(self, X: pd.DataFrame) -> pd.Series:
        for column in self._time_columns:
            if column not in X.columns:
                continue
            series = X[column]
            if column == "month":
                parsed = pd.to_numeric(series, errors="coerce")
            else:
                parsed = pd.to_datetime(series, errors="coerce")
                if parsed.notna().sum() > 0:
                    numeric_order = parsed.map(lambda value: value.value if pd.notna(value) else np.nan)
                    numeric_order = numeric_order.fillna(numeric_order.median()).fillna(0)
                    return pd.Series(numeric_order, index=X.index)
            if parsed.notna().sum() > 0:
                return pd.Series(parsed, index=X.index)
        if "days_since_last_product_order" in X.columns:
            fallback = pd.to_numeric(X["days_since_last_product_order"], errors="coerce").fillna(0)
            return fallback * -1
        return pd.Series(np.arange(len(X)), index=X.index)

    @staticmethod
    def _time_aware_split_indices(order: pd.Series, total_rows: int) -> Tuple[np.ndarray, np.ndarray]:
        if total_rows < 2:
            single_index = np.arange(total_rows)
            return single_index, single_index
        ordered_index = order.sort_values(kind="mergesort").index.to_numpy()
        split_point = max(int(total_rows * 0.8), 1)
        split_point = min(split_point, total_rows - 1)
        train_idx = ordered_index[:split_point]
        val_idx = ordered_index[split_point:]
        return train_idx, val_idx

    def _build_forecast_dates(self, base_df: pd.DataFrame) -> pd.Series:
        for column in self._time_columns:
            if column not in base_df.columns:
                continue
            parsed = pd.to_datetime(base_df[column], errors="coerce")
            if parsed.notna().sum() == 0:
                continue
            return (parsed + pd.Timedelta(days=30)).dt.date.astype("string")
        fallback_date = pd.Timestamp.utcnow().date().isoformat()
        return pd.Series([fallback_date] * len(base_df), index=base_df.index, dtype="string")


def _load_prepared_sales(mode: str, project_root: Optional[Path] = None) -> pd.DataFrame:
    project_root = (
        Path(project_root).resolve()
        if project_root is not None
        else Path(__file__).resolve().parents[3]
    )
    config = FeatureConfig(processed_data_dir=project_root / "backend" / "processed_data")
    source_frame = load_feature_source_frame(mode, config)
    return prepare_feature_source_frame(source_frame)


def _build_snapshot_dates(sales: pd.DataFrame) -> List[pd.Timestamp]:
    if sales.empty:
        return []
    max_sale_date = sales["sale_date"].max().normalize()
    first_month_end = sales["sale_date"].min().to_period("M").to_timestamp("M")
    all_month_ends = pd.date_range(first_month_end, max_sale_date, freq="ME")
    snapshot_dates = [
        ts.normalize()
        for ts in all_month_ends
        if ts.normalize() + pd.Timedelta(days=30) <= max_sale_date
    ]
    return snapshot_dates


def _build_forward_target(
    sales: pd.DataFrame,
    snapshot_date: pd.Timestamp,
) -> pd.DataFrame:
    horizon_end = snapshot_date + pd.Timedelta(days=30)
    window = sales.loc[sales["sale_date"].gt(snapshot_date) & sales["sale_date"].le(horizon_end)]
    if window.empty:
        return pd.DataFrame(columns=["client_id", "product_id", "target_30d_sales"])
    return (
        window.groupby(["client_id", "product_id"], dropna=False)["amount"]
        .sum()
        .reset_index()
        .rename(columns={"amount": "target_30d_sales"})
    )


def _attach_snapshot_metadata(df: pd.DataFrame, snapshot_date: pd.Timestamp) -> pd.DataFrame:
    enriched = df.copy()
    enriched["snapshot_date"] = pd.Timestamp(snapshot_date)
    enriched["snapshot_month"] = int(snapshot_date.month)
    enriched["snapshot_quarter"] = int(snapshot_date.quarter)
    return enriched


def build_historical_training_panel(
    sales: pd.DataFrame,
    *,
    n_clusters: int = 5,
    random_state: int = 42,
) -> pd.DataFrame:
    """Build the monthly walk-forward training panel without future leakage."""
    if sales.empty:
        raise ValueError("Cannot build training panel from empty sales data")
    snapshot_dates = _build_snapshot_dates(sales)
    if not snapshot_dates:
        raise ValueError("No monthly snapshots with a complete 30-day horizon were found")

    forecaster = DemandForecaster()
    frames: List[pd.DataFrame] = []
    for snapshot_date in snapshot_dates:
        snapshot_sales = sales.loc[sales["sale_date"].le(snapshot_date)].copy()
        client_df = _attach_snapshot_metadata(build_client_features(snapshot_sales), snapshot_date)
        product_df = _attach_snapshot_metadata(build_product_features(snapshot_sales), snapshot_date)
        client_product_df = _attach_snapshot_metadata(
            build_client_product_features(snapshot_sales),
            snapshot_date,
        )

        clusterer = CommodityCustomerCluster(n_clusters=n_clusters, random_state=random_state)
        cluster_matrix = clusterer.prepare_matrix(client_df)
        clusterer.fit(cluster_matrix, raw_df=client_df)
        labels = clusterer.predict(cluster_matrix)
        cluster_df = pd.DataFrame(
            {
                "customer_id": client_df["client_id"].astype("string"),
                "cluster_id": labels.astype(int),
            }
        )

        merged = forecaster.merge_feature_tables(
            client_product_df,
            product_df,
            client_df,
            cluster_df,
            source_names={
                "client_product": "snapshot_client_product_features",
                "product": "snapshot_products",
                "client": "snapshot_clients",
            },
            require_target=False,
        )
        target_df = _build_forward_target(sales, snapshot_date)
        merged = merged.merge(
            target_df.rename(columns={"client_id": "customer_id"}),
            how="left",
            on=["customer_id", "product_id"],
            validate="many_to_one",
        )
        merged["target_30d_sales"] = pd.to_numeric(merged["target_30d_sales"], errors="coerce").fillna(0.0)
        merged["baseline_30d_sales"] = pd.to_numeric(merged["rolling_sales_30d"], errors="coerce").fillna(0.0)
        merged["snapshot_date"] = pd.Timestamp(snapshot_date)
        merged["snapshot_month"] = int(snapshot_date.month)
        merged["snapshot_quarter"] = int(snapshot_date.quarter)
        frames.append(merged)

    panel = pd.concat(frames, ignore_index=True)
    panel = _normalize_frame_types(panel)
    panel["target_30d_sales"] = pd.to_numeric(panel["target_30d_sales"], errors="coerce").fillna(0.0)
    panel["baseline_30d_sales"] = pd.to_numeric(panel["baseline_30d_sales"], errors="coerce").fillna(0.0)
    panel = panel.sort_values(["snapshot_date", "customer_id", "product_id"]).reset_index(drop=True)
    return panel


def _build_latest_snapshot_frame(
    mode: str,
    project_root: Optional[Path] = None,
) -> Tuple[pd.DataFrame, pd.Timestamp]:
    project_root = (
        Path(project_root).resolve()
        if project_root is not None
        else Path(__file__).resolve().parents[3]
    )
    sales = _load_prepared_sales(mode, project_root)
    latest_snapshot_date = sales["sale_date"].max().normalize()
    features_dir = project_root / "backend" / "processed_data" / mode
    commodity_output_dir = project_root / "backend" / "commodity-ai-engine" / "output" / mode
    forecaster = DemandForecaster()
    latest_frame = forecaster.load_inputs(features_dir, commodity_output_dir)
    latest_frame["snapshot_date"] = latest_snapshot_date
    latest_frame["snapshot_month"] = int(latest_snapshot_date.month)
    latest_frame["snapshot_quarter"] = int(latest_snapshot_date.quarter)
    return latest_frame, latest_snapshot_date


def run_customer_clustering(mode: str, project_root: Optional[Path] = None) -> Path:
    """Run the real customer clustering component for the latest available feature snapshot."""
    project_root = (
        Path(project_root).resolve()
        if project_root is not None
        else Path(__file__).resolve().parents[3]
    )
    features_dir = project_root / "backend" / "processed_data" / mode
    commodity_output_dir = project_root / "backend" / "commodity-ai-engine" / "output" / mode

    clusterer = CommodityCustomerCluster()
    client_df = clusterer.load_inputs(features_dir)
    matrix = clusterer.prepare_matrix(client_df)
    clusterer.fit(matrix, raw_df=client_df)
    labels = clusterer.predict(matrix)
    profiles = clusterer.build_cluster_profiles(client_df, labels)
    assignments_path, _ = clusterer.save_outputs(
        commodity_output_dir,
        client_df[clusterer._resolve_customer_id_column(client_df.columns)],
        labels,
        profiles,
    )
    metrics_path = _write_json(
        clusterer.compute_metrics(matrix, labels),
        _metrics_dir(commodity_output_dir) / "cluster_metrics.json",
    )
    logger.info("Saved clustering metrics to %s", metrics_path)
    return assignments_path


def _run_forecast_backtest(
    panel: pd.DataFrame,
    *,
    warmup_snapshots: int = 12,
) -> Tuple[pd.DataFrame, dict]:
    if panel.empty:
        raise ValueError("Cannot run backtest on an empty panel")
    snapshot_dates = sorted(pd.to_datetime(panel["snapshot_date"]).dropna().unique())
    if len(snapshot_dates) <= warmup_snapshots:
        raise ValueError(
            f"Backtest requires more than {warmup_snapshots} snapshots; found {len(snapshot_dates)}"
        )

    prediction_frames: List[pd.DataFrame] = []
    for index in range(warmup_snapshots, len(snapshot_dates)):
        train_dates = snapshot_dates[:index]
        validation_date = snapshot_dates[index]
        train_df = panel.loc[panel["snapshot_date"].isin(train_dates)].reset_index(drop=True)
        validation_df = panel.loc[panel["snapshot_date"].eq(validation_date)].reset_index(drop=True)

        forecaster = DemandForecaster()
        X_train, y_train = forecaster.build_training_frame(train_df)
        forecaster.train(X_train, y_train)

        validation_raw = forecaster.build_prediction_frame(validation_df)
        validation_pred = forecaster.predict(validation_raw)
        validation_confidence = forecaster.estimate_confidence(validation_raw, validation_pred)
        baseline = pd.to_numeric(validation_df["baseline_30d_sales"], errors="coerce").fillna(0.0).to_numpy(dtype=float)
        product_key = forecaster._resolved_product_key(validation_df)

        prediction_frame = pd.DataFrame(
            {
                "snapshot_date": validation_df["snapshot_date"].astype("string"),
                "customer_id": validation_df["customer_id"].astype("string"),
                product_key: validation_df[product_key].astype("string"),
                "cluster_id": pd.to_numeric(validation_df["cluster_id"], errors="coerce").fillna(-1).astype(int),
                "actual_30d_sales": pd.to_numeric(validation_df["target_30d_sales"], errors="coerce").fillna(0.0),
                "predicted_30d_sales": validation_pred,
                "baseline_30d_sales": baseline,
                "forecast_confidence": validation_confidence,
            }
        )
        prediction_frames.append(prediction_frame)

    backtest_predictions = pd.concat(prediction_frames, ignore_index=True)
    metrics = _compute_regression_metrics(
        backtest_predictions["actual_30d_sales"],
        backtest_predictions["predicted_30d_sales"],
        baseline=backtest_predictions["baseline_30d_sales"],
    )
    metrics.update(
        {
            "warmup_snapshots": int(warmup_snapshots),
            "evaluated_snapshots": int(len(snapshot_dates) - warmup_snapshots),
            "evaluated_rows": int(len(backtest_predictions)),
            "latest_evaluated_snapshot": str(pd.to_datetime(backtest_predictions["snapshot_date"]).max().date()),
            "passes_baseline": bool(
                metrics["rmse_improvement_vs_baseline"] > 0
                and metrics["wmape_improvement_vs_baseline"] > 0
            ),
        }
    )
    return backtest_predictions, metrics


def run_model_evaluation(mode: str, project_root: Optional[Path] = None) -> dict[str, Path]:
    """Run historical backtesting and produce the latest operational forecast."""
    if mode != "historical":
        raise NotImplementedError(
            "Real forecast evaluation is only implemented for historical mode."
        )
    project_root = (
        Path(project_root).resolve()
        if project_root is not None
        else Path(__file__).resolve().parents[3]
    )
    commodity_output_dir = project_root / "backend" / "commodity-ai-engine" / "output" / mode
    commodity_output_dir.mkdir(parents=True, exist_ok=True)

    run_customer_clustering(mode, project_root)

    sales = _load_prepared_sales(mode, project_root)
    panel = build_historical_training_panel(sales)
    backtest_predictions, forecast_metrics = _run_forecast_backtest(panel)

    backtest_path = _write_parquet(
        backtest_predictions,
        _metrics_dir(commodity_output_dir) / "forecast_backtest_predictions.parquet",
    )
    metrics_path = _write_json(
        forecast_metrics,
        _metrics_dir(commodity_output_dir) / "forecast_metrics.json",
    )

    latest_frame, latest_snapshot_date = _build_latest_snapshot_frame(mode, project_root)
    final_forecaster = DemandForecaster()
    X_all, y_all = final_forecaster.build_training_frame(panel)
    final_forecaster.train(X_all, y_all)
    latest_raw = final_forecaster.build_prediction_frame(latest_frame)
    latest_pred = final_forecaster.predict(latest_raw)
    latest_confidence = final_forecaster.estimate_confidence(latest_raw, latest_pred)
    forecast_path = final_forecaster.save_outputs(
        commodity_output_dir,
        latest_frame,
        latest_pred,
        latest_confidence,
    )
    logger.info("Latest operational forecast snapshot date: %s", latest_snapshot_date.date())
    return {
        "forecast_output": forecast_path,
        "forecast_metrics": metrics_path,
        "backtest_predictions": backtest_path,
    }


class DemandLeakageDetector:
    """Detects demand leakage (expected > observed) indicating potential competitor capture."""

    def __init__(self, min_confidence_threshold: float = 0.5):
        self.min_confidence_threshold = min_confidence_threshold

    def compute_leakage(
        self,
        predicted_consumption: pd.Series,
        observed_consumption: pd.Series,
        customer_volatility: pd.Series,
        model_confidence: float = 0.85,
    ) -> pd.DataFrame:
        results = pd.DataFrame(
            {
                "predicted": predicted_consumption,
                "observed": observed_consumption,
            }
        )
        results["base_gap"] = np.where(
            results["predicted"] > 0,
            (results["predicted"] - results["observed"]) / results["predicted"],
            0,
        )
        results["leakage_score"] = (
            np.maximum(results["base_gap"], 0)
            * customer_volatility.fillna(1.0)
            * model_confidence
        ).clip(0, 1)
        return results

    def filter_significant_leakage(
        self,
        leakage_df: pd.DataFrame,
        min_gap_units: int = 10,
    ) -> pd.DataFrame:
        return leakage_df[
            (leakage_df["leakage_score"] > self.min_confidence_threshold)
            & ((leakage_df["predicted"] - leakage_df["observed"]) >= min_gap_units)
        ]


class CaptureScoringEngine:
    """Scores and ranks capture opportunities."""

    def __init__(self):
        self.weights = {
            "leakage": 0.40,
            "customer_value": 0.30,
            "urgency": 0.20,
            "confidence": 0.10,
        }

    def compute_customer_value(
        self,
        customer_id: str,
        clients_df: pd.DataFrame,
        historical_spend: pd.Series,
    ) -> float:
        if "customer_total_revenue" not in clients_df.columns:
            return 0.0
        customer_row = clients_df.loc[clients_df["client_id"].astype("string").eq(str(customer_id))]
        if customer_row.empty:
            return 0.0
        revenue = float(pd.to_numeric(customer_row["customer_total_revenue"], errors="coerce").fillna(0).iloc[0])
        max_revenue = float(pd.to_numeric(clients_df["customer_total_revenue"], errors="coerce").fillna(0).max()) + 1e-9
        return float(np.clip(revenue / max_revenue, 0, 1))

    def compute_urgency(self, leakage_df: pd.DataFrame) -> float:
        if leakage_df.empty:
            return 0.0
        gap = pd.to_numeric(leakage_df["predicted"], errors="coerce").fillna(0) - pd.to_numeric(
            leakage_df["observed"], errors="coerce"
        ).fillna(0)
        score = float(np.tanh(gap.abs().mean() / 100.0))
        return float(np.clip(score, 0, 1))

    def score_opportunities(
        self,
        leakage_df: pd.DataFrame,
        customers_df: pd.DataFrame,
        historical_spend: pd.Series,
        forecaster: DemandForecaster,
    ) -> pd.DataFrame:
        scored = leakage_df.copy()
        scored["leakage_norm"] = leakage_df["leakage_score"]
        scored["value_norm"] = leakage_df.index.map(
            lambda x: self.compute_customer_value(x, customers_df, historical_spend)
        )
        scored["urgency_norm"] = leakage_df.index.map(
            lambda x: self.compute_urgency(leakage_df.loc[[x]])
        )
        scored["confidence_norm"] = forecaster.base_confidence_
        scored["capture_score"] = (
            scored["leakage_norm"] * self.weights["leakage"]
            + scored["value_norm"] * self.weights["customer_value"]
            + scored["urgency_norm"] * self.weights["urgency"]
            + scored["confidence_norm"] * self.weights["confidence"]
        ) * 100
        scored = scored.sort_values("capture_score", ascending=False)
        scored["priority_rank"] = range(1, len(scored) + 1)
        return scored

    def generate_action_recommendations(self, scored_df: pd.DataFrame) -> Dict[str, str]:
        actions = {}
        for idx, row in scored_df.iterrows():
            if row["capture_score"] > 80:
                action = "URGENT: High-value competitor capture - sales call within 24h"
            elif row["capture_score"] > 60:
                action = "HIGH: Significant demand gap - schedule follow-up call"
            elif row["capture_score"] > 40:
                action = "MEDIUM: Monitor for competitive activity"
            else:
                action = "LOW: Watch for changes in pattern"
            actions[idx] = action
        return actions


class CommoditySignalGenerator:
    """
    Legacy orchestration wrapper.

    The production path for clustering and forecasting now lives in
    `run_customer_clustering()` and `run_model_evaluation()`.
    """

    def __init__(self, sales_df: pd.DataFrame, clients_df: pd.DataFrame, products_df: pd.DataFrame):
        self.sales_df = sales_df
        self.clients_df = clients_df
        self.products_df = products_df
        self.leakage_detector = DemandLeakageDetector()
        self.scorer = CaptureScoringEngine()

    def generate_signals(self) -> List[CommoditySignal]:
        raise NotImplementedError(
            "CommoditySignalGenerator is not wired to the new historical evaluation path yet. "
            "Use run_customer_clustering() and run_model_evaluation() instead."
        )

    def export_signals(self, signals: List[CommoditySignal], output_path: str) -> None:
        data = [asdict(signal) for signal in signals]
        with open(output_path, "w", encoding="utf-8") as handle:
            json.dump(data, handle, indent=2)
        logger.info("Exported %s signals to %s", len(signals), output_path)


def run_consumption_forecast(mode: str, project_root: Optional[Path] = None) -> Path:
    """Run the historical evaluation pipeline and return the latest forecast artifact."""
    artifacts = run_model_evaluation(mode, project_root)
    return artifacts["forecast_output"]


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Run the commodity AI engine components")
    parser.add_argument(
        "--mode",
        default="historical",
        choices=("historical", "daily"),
        help="Input/output mode for the commodity pipeline",
    )
    parser.add_argument(
        "--task",
        default="forecast",
        choices=("clustering", "forecast", "evaluation"),
        help="Commodity task to execute",
    )
    args = parser.parse_args()

    if args.task == "clustering":
        output_path = run_customer_clustering(args.mode)
        logger.info("Customer clustering completed: %s", output_path)
    elif args.task == "evaluation":
        artifacts = run_model_evaluation(args.mode)
        logger.info("Commodity evaluation completed: %s", artifacts)
    else:
        output_path = run_consumption_forecast(args.mode)
        logger.info("Consumption forecast completed: %s", output_path)
