"""
Commodity AI Engine - Demand Leakage & Capture Opportunity Detection
INIBSA Smart Demand Signals Platform
"""

import importlib.util
import json
import logging
from dataclasses import dataclass, asdict
from datetime import datetime, timedelta
from enum import Enum
from pathlib import Path
from typing import Dict, Iterable, List, Optional, Tuple

import numpy as np
import pandas as pd
import lightgbm as lgb
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


class CustomerCluster(Enum):
    """Customer behavioral segments for commodity products"""
    LOYAL_HIGH_VOLUME = 0
    PROMISCUOUS_BUYERS = 1
    LOW_ENGAGEMENT = 2
    GROWING_ACCOUNTS = 3
    UNSTABLE_BEHAVIOR = 4


@dataclass
class CommoditySignal:
    """Signal generated by commodity engine for a specific customer/product"""
    customer_id: str
    product_family: str
    signal_type: str = "demand_leakage"
    leakage_score: float = 0.0
    predicted_monthly_consumption: float = 0.0
    observed_monthly_consumption: float = 0.0
    gap_units: float = 0.0
    estimated_lost_revenue: float = 0.0
    customer_cluster: str = ""
    urgency: float = 0.0
    confidence: float = 0.0
    recommended_action: str = ""
    timeline: List[str] = None
    
    def to_dict(self):
        """Convert to dictionary for JSON serialization"""
        data = asdict(self)
        return data


class CommodityCustomerCluster:
    """
    KMeans clustering for commodity product customers.
    Segments customers by purchasing behavior using precomputed feature tables.
    """

    _cluster_feature_columns: Tuple[str, ...] = (
        "customer_total_revenue",
        "customer_total_orders",
        "customer_avg_ticket",
        "customer_frequency",
        "days_since_last_order",
        "return_rate_30d",
        "campaign_lift",
        "coefficient_variation_30d",
    )
    _zero_fill_columns: Tuple[str, ...] = (
        "return_rate_30d",
        "campaign_lift",
    )
    _customer_id_columns: Tuple[str, ...] = (
        "client_id",
        "customer_id",
    )

    def __init__(self, n_clusters: int = 5, random_state: int = 42):
        self.n_clusters = n_clusters
        self.random_state = random_state
        self.kmeans = KMeans(n_clusters=n_clusters, random_state=random_state)
        self.scaler = StandardScaler()

    def load_inputs(self, features_dir: Path) -> pd.DataFrame:
        """Load client-level feature tables for clustering."""
        if not features_dir.exists():
            raise FileNotFoundError(f"Features directory not found: {features_dir}")

        client_path = features_dir / "client_features.parquet"
        if not client_path.exists():
            raise FileNotFoundError(f"Missing required file: {client_path}")

        logger.info("Loading client features from %s", client_path)
        df = pd.read_parquet(client_path)
        if df.empty:
            raise ValueError("client_features.parquet is empty")

        optional_path = features_dir / "client_product_features.parquet"
        if optional_path.exists():
            logger.info(
                "Optional client_product_features.parquet found at %s (not used for clustering)",
                optional_path,
            )

        logger.info("Loaded %s rows with %s columns", len(df), len(df.columns))
        return df

    def validate_schema(self, df: pd.DataFrame) -> None:
        """Validate the input schema against the Excel definition."""
        if df.empty:
            raise ValueError("Input features DataFrame is empty")

        schema_columns = self._load_schema_columns()
        missing_in_schema = sorted(set(self._cluster_feature_columns) - set(schema_columns))
        if missing_in_schema:
            missing = ", ".join(missing_in_schema)
            logger.error("Schema validation failed; missing in Excel schema: %s", missing)
            raise ValueError(f"Excel schema missing required clustering columns: {missing}")

        missing_in_df = sorted(set(self._cluster_feature_columns) - set(df.columns))
        if missing_in_df:
            missing = ", ".join(missing_in_df)
            logger.error("Schema validation failed; missing in input data: %s", missing)
            raise ValueError(f"Input data missing required clustering columns: {missing}")

        id_column = self._resolve_customer_id_column(df.columns)
        if id_column is None:
            logger.error("Schema validation failed; missing customer identifier column")
            raise ValueError("Input data must include client_id or customer_id")

        logger.info("Schema validation passed using identifier column %s", id_column)

    def prepare_matrix(self, df: pd.DataFrame) -> pd.DataFrame:
        """Prepare standardized numeric feature matrix for clustering."""
        self.validate_schema(df)
        features = self._coerce_and_fill(df.loc[:, self._cluster_feature_columns])

        if hasattr(self.scaler, "mean_"):
            scaled = self.scaler.transform(features)
            logger.info("Scaled features using existing scaler")
        else:
            scaled = self.scaler.fit_transform(features)
            logger.info("Fitted scaler and standardized features")

        return pd.DataFrame(scaled, columns=self._cluster_feature_columns, index=df.index)

    def fit(self, X: pd.DataFrame) -> None:
        """Fit KMeans clustering on a prepared feature matrix."""
        if X is None or len(X) == 0:
            raise ValueError("Cannot fit clustering on empty feature matrix")

        self.kmeans.fit(X)
        counts = np.bincount(self.kmeans.labels_, minlength=self.n_clusters)
        if (counts == 0).any():
            raise ValueError("At least one cluster has zero customers; adjust n_clusters")

        logger.info("Clustering fitted with %s clusters", self.n_clusters)

    def predict(self, X: pd.DataFrame) -> np.ndarray:
        """Predict cluster assignments for a prepared feature matrix."""
        if not hasattr(self.kmeans, "cluster_centers_"):
            raise ValueError("KMeans model is not fitted yet")
        return self.kmeans.predict(X)

    def build_cluster_profiles(self, raw_df: pd.DataFrame, labels: np.ndarray) -> pd.DataFrame:
        """Build mean profiles and counts for each cluster."""
        if raw_df.empty:
            raise ValueError("Cannot build profiles from empty data")

        self.validate_schema(raw_df)

        profiles_source = self._coerce_and_fill(raw_df.loc[:, self._cluster_feature_columns])
        profiles_source["cluster_id"] = labels

        means = profiles_source.groupby("cluster_id")[self._cluster_feature_columns].mean()
        counts = profiles_source.groupby("cluster_id").size().rename("count")
        profiles = means.join(counts).reset_index()

        if (profiles["count"] == 0).any():
            raise ValueError("Cluster profiles contain empty clusters")

        logger.info("Built cluster profiles for %s clusters", len(profiles))
        return profiles

    def save_outputs(
        self,
        output_dir: Path,
        customer_ids: pd.Series,
        labels: np.ndarray,
        profiles: pd.DataFrame,
    ) -> None:
        """Persist cluster assignments and profiles to parquet files."""
        output_dir.mkdir(parents=True, exist_ok=True)
        assignments = pd.DataFrame(
            {
                "customer_id": customer_ids.astype("string"),
                "cluster_id": labels.astype(int),
            }
        )

        assignments_path = output_dir / "cluster_assignments.parquet"
        profiles_path = output_dir / "cluster_profiles.parquet"

        self._write_parquet(assignments, assignments_path)
        self._write_parquet(profiles, profiles_path)

        logger.info("Saved cluster assignments to %s", assignments_path)
        logger.info("Saved cluster profiles to %s", profiles_path)

    def get_cluster_name(self, cluster_id: int) -> str:
        """Get human-readable cluster name."""
        return CustomerCluster(cluster_id).name.lower()

    @staticmethod
    def _parquet_engine() -> str:
        if importlib.util.find_spec("pyarrow") is not None:
            return "pyarrow"
        if importlib.util.find_spec("fastparquet") is not None:
            return "fastparquet"
        raise RuntimeError(
            "Parquet output requires either 'pyarrow' or 'fastparquet' to be installed."
        )

    def _write_parquet(self, df: pd.DataFrame, output_path: Path) -> None:
        df.to_parquet(
            output_path,
            index=False,
            compression="snappy",
            engine=self._parquet_engine(),
        )

    @staticmethod
    def _schema_path() -> Path:
        return Path(__file__).resolve().parents[2] / "data_processing" / "inibsa_feature_tables.xlsx"

    def _load_schema_columns(self) -> List[str]:
        schema_path = self._schema_path()
        if not schema_path.exists():
            raise FileNotFoundError(f"Schema file not found: {schema_path}")

        try:
            schema_df = pd.read_excel(schema_path, sheet_name="clients")
        except ImportError as exc:
            raise ImportError(
                "Reading inibsa_feature_tables.xlsx requires 'openpyxl' to be installed"
            ) from exc
        except ValueError as exc:
            raise ValueError("Sheet 'clients' not found in schema workbook") from exc

        if "Column" not in schema_df.columns:
            raise ValueError("Schema sheet must include a 'Column' header")

        return (
            schema_df["Column"]
            .dropna()
            .astype(str)
            .str.strip()
            .tolist()
        )

    def _coerce_and_fill(self, features: pd.DataFrame) -> pd.DataFrame:
        filled = features.copy()
        for column in self._cluster_feature_columns:
            filled[column] = pd.to_numeric(filled[column], errors="coerce")

        for column in self._zero_fill_columns:
            filled[column] = filled[column].fillna(0)

        for column in self._cluster_feature_columns:
            if column in self._zero_fill_columns:
                continue
            median_value = filled[column].median()
            if pd.isna(median_value):
                median_value = 0
            filled[column] = filled[column].fillna(median_value)

        if filled.isna().any().any():
            logger.warning("Remaining NaNs found after filling; defaulting to 0")
            filled = filled.fillna(0)

        return filled

    def _resolve_customer_id_column(self, columns: Iterable[str]) -> Optional[str]:
        column_set = set(columns)
        for candidate in self._customer_id_columns:
            if candidate in column_set:
                return candidate
        return None


class DemandForecaster:
    """
    LightGBM-based demand forecasting for commodity products.
    Predicts expected monthly consumption.
    """
    
    def __init__(self, model_params: Optional[Dict] = None):
        self.model = None
        self.feature_names = None
        self.model_params = model_params or {
            'learning_rate': 0.05,
            'num_leaves': 31,
            'max_depth': 5,
            'objective': 'regression',
            'metric': 'rmse'
        }
        
    def prepare_features(self, sales_df: pd.DataFrame, clustering_results: pd.DataFrame,
                        clients_df: pd.DataFrame) -> Tuple[pd.DataFrame, pd.Series]:
        """
        Prepare forecasting features.
        
        Features include:
        - Rolling statistics (7d, 30d volume and frequency)
        - Seasonality and trend
        - Customer cluster
        - Product family
        - Customer metadata (size, tier)
        
        Returns:
            X: Features DataFrame
            y: Target (expected consumption) Series
        """
        # TODO: Implement feature engineering for forecasting
        # Rolling 7d, 30d averages
        # Seasonality extraction
        # Trend calculation
        pass
    
    def train(self, X_train: pd.DataFrame, y_train: pd.Series):
        """Train LightGBM model"""
        self.feature_names = X_train.columns.tolist()
        train_data = lgb.Dataset(X_train, label=y_train, feature_name=self.feature_names)
        self.model = lgb.train(self.model_params, train_data, num_boost_round=100)
        logger.info("Demand forecaster trained")
        
    def predict(self, X: pd.DataFrame) -> np.ndarray:
        """Predict expected consumption"""
        if self.model is None:
            raise ValueError("Model not trained yet")
        return self.model.predict(X)
    
    def get_feature_importance(self) -> Dict[str, float]:
        """Get feature importance from model"""
        if self.model is None:
            return {}
        importance = self.model.feature_importance()
        return {name: imp for name, imp in zip(self.feature_names, importance)}


class DemandLeakageDetector:
    """
    Detects demand leakage (expected > observed) indicating potential competitor capture.
    """
    
    def __init__(self, min_confidence_threshold: float = 0.5):
        self.min_confidence_threshold = min_confidence_threshold
        
    def compute_leakage(self, 
                       predicted_consumption: pd.Series,
                       observed_consumption: pd.Series,
                       customer_volatility: pd.Series,
                       model_confidence: float = 0.85) -> pd.DataFrame:
        """
        Compute demand leakage for customers.
        
        Formula:
            base_gap = (predicted - observed) / predicted
            leakage_score = base_gap × volatility_factor × confidence
        
        Args:
            predicted_consumption: Expected monthly consumption
            observed_consumption: Actual monthly consumption
            customer_volatility: Historical variance in purchases
            model_confidence: Confidence in forecasting model
            
        Returns:
            DataFrame with leakage metrics
        """
        results = pd.DataFrame({
            'predicted': predicted_consumption,
            'observed': observed_consumption
        })
        
        # Avoid division by zero
        results['base_gap'] = np.where(
            results['predicted'] > 0,
            (results['predicted'] - results['observed']) / results['predicted'],
            0
        )
        
        # Normalize by customer volatility and model confidence
        results['leakage_score'] = (
            np.maximum(results['base_gap'], 0)  # Only positive gaps
            * customer_volatility.fillna(1.0)   # Account for variance
            * model_confidence
        )
        
        # Clip to 0-1 range
        results['leakage_score'] = results['leakage_score'].clip(0, 1)
        
        return results
    
    def filter_significant_leakage(self, leakage_df: pd.DataFrame, 
                                   min_gap_units: int = 10) -> pd.DataFrame:
        """Filter to significant leakage events only"""
        return leakage_df[
            (leakage_df['leakage_score'] > self.min_confidence_threshold) &
            ((leakage_df['predicted'] - leakage_df['observed']) >= min_gap_units)
        ]


class CaptureScoringEngine:
    """
    Scores and ranks capture opportunities.
    Combines leakage data with business metrics to prioritize sales actions.
    """
    
    def __init__(self):
        self.weights = {
            'leakage': 0.40,
            'customer_value': 0.30,
            'urgency': 0.20,
            'confidence': 0.10
        }
        
    def compute_customer_value(self, customer_id: str, clients_df: pd.DataFrame,
                              historical_spend: pd.Series) -> float:
        """Normalize customer value to 0-1 scale"""
        # TODO: Implement based on spend, tier, clinic size
        # Should return normalized score 0-1
        pass
    
    def compute_urgency(self, leakage_df: pd.DataFrame) -> float:
        """
        Compute urgency based on:
        - Magnitude of leakage
        - Trend (increasing vs stable)
        - Days since alert
        """
        # TODO: Implement urgency scoring
        # Larger leakage = more urgent
        # Increasing trend = more urgent
        pass
    
    def score_opportunities(self, leakage_df: pd.DataFrame,
                           customers_df: pd.DataFrame,
                           historical_spend: pd.Series,
                           forecaster: DemandForecaster) -> pd.DataFrame:
        """
        Compute overall capture opportunity score.
        
        Formula:
            score = (leakage × 0.40) + (value × 0.30) + (urgency × 0.20) + (confidence × 0.10)
        
        Returns:
            DataFrame with scores ranked by opportunity
        """
        scored = leakage_df.copy()
        
        # Normalize components
        scored['leakage_norm'] = leakage_df['leakage_score']
        scored['value_norm'] = leakage_df.index.map(
            lambda x: self.compute_customer_value(x, customers_df, historical_spend)
        )
        scored['urgency_norm'] = leakage_df.index.map(
            lambda x: self.compute_urgency(leakage_df.loc[[x]])
        )
        scored['confidence_norm'] = 0.85  # From forecaster
        
        # Weighted score
        scored['capture_score'] = (
            scored['leakage_norm'] * self.weights['leakage'] +
            scored['value_norm'] * self.weights['customer_value'] +
            scored['urgency_norm'] * self.weights['urgency'] +
            scored['confidence_norm'] * self.weights['confidence']
        ) * 100
        
        # Rank by score
        scored = scored.sort_values('capture_score', ascending=False)
        scored['priority_rank'] = range(1, len(scored) + 1)
        
        return scored
    
    def generate_action_recommendations(self, scored_df: pd.DataFrame) -> Dict[str, str]:
        """Generate human-readable recommended actions for sales team"""
        actions = {}
        for idx, row in scored_df.iterrows():
            if row['capture_score'] > 80:
                action = "URGENT: High-value competitor capture - sales call within 24h"
            elif row['capture_score'] > 60:
                action = "HIGH: Significant demand gap - schedule follow-up call"
            elif row['capture_score'] > 40:
                action = "MEDIUM: Monitor for competitive activity"
            else:
                action = "LOW: Watch for changes in pattern"
            actions[idx] = action
        return actions


class CommoditySignalGenerator:
    """
    Orchestrates the complete commodity engine pipeline.
    Combines all components to generate actionable signals.
    """
    
    def __init__(self, sales_df: pd.DataFrame, clients_df: pd.DataFrame, 
                products_df: pd.DataFrame):
        self.sales_df = sales_df
        self.clients_df = clients_df
        self.products_df = products_df
        
        self.clusterer = CommodityCustomerCluster()
        self.forecaster = DemandForecaster()
        self.leakage_detector = DemandLeakageDetector()
        self.scorer = CaptureScoringEngine()
        
    def generate_signals(self) -> List[CommoditySignal]:
        """
        Run complete pipeline and generate signals.
        
        Steps:
        1. Cluster customers
        2. Forecast demand
        3. Detect leakage
        4. Score opportunities
        5. Generate explanations
        
        Returns:
            List of CommoditySignal objects
        """
        logger.info("Starting commodity engine pipeline...")
        
        # Step 1: Clustering
        logger.info("Step 1: Clustering customers...")
        cluster_features = self.clusterer.prepare_features(self.sales_df, self.clients_df)
        self.clusterer.fit(cluster_features)
        cluster_assignments = self.clusterer.predict(cluster_features)
        
        # Step 2: Forecasting
        logger.info("Step 2: Forecasting demand...")
        forecast_features, forecast_target = self.forecaster.prepare_features(
            self.sales_df, cluster_assignments, self.clients_df
        )
        self.forecaster.train(forecast_features, forecast_target)
        predictions = self.forecaster.predict(forecast_features)
        
        # Step 3: Leakage detection
        logger.info("Step 3: Detecting demand leakage...")
        observed = self._get_observed_consumption()
        leakage_results = self.leakage_detector.compute_leakage(
            pd.Series(predictions),
            observed
        )
        
        # Step 4: Scoring
        logger.info("Step 4: Scoring opportunities...")
        scored = self.scorer.score_opportunities(
            leakage_results, self.clients_df, observed, self.forecaster
        )
        actions = self.scorer.generate_action_recommendations(scored)
        
        # Step 5: Generate signals
        logger.info("Step 5: Generating signals...")
        signals = self._create_signals(scored, actions)
        
        logger.info(f"Generated {len(signals)} signals")
        return signals
    
    def _get_observed_consumption(self) -> pd.Series:
        """Extract observed consumption from sales data"""
        # TODO: Implement - group sales by customer/period
        pass
    
    def _create_signals(self, scored_df: pd.DataFrame, actions: Dict[str, str]) -> List[CommoditySignal]:
        """Create CommoditySignal objects from scored data"""
        signals = []
        for customer_id, row in scored_df.iterrows():
            signal = CommoditySignal(
                customer_id=str(customer_id),
                product_family=row.get('product_family', 'Unknown'),
                signal_type='demand_leakage',
                leakage_score=float(row['leakage_score']),
                predicted_monthly_consumption=float(row['predicted']),
                observed_monthly_consumption=float(row['observed']),
                gap_units=float(row['predicted'] - row['observed']),
                estimated_lost_revenue=float((row['predicted'] - row['observed']) * 8),  # Avg price
                customer_cluster=row.get('cluster', 'Unknown'),
                urgency=float(row['urgency_norm']),
                confidence=0.85,
                recommended_action=actions.get(customer_id, ""),
                timeline=self._build_timeline(customer_id)
            )
            signals.append(signal)
        return signals
    
    def _build_timeline(self, customer_id: str) -> List[str]:
        """Build timeline of customer behavior"""
        # TODO: Implement timeline reconstruction from historical data
        return ["Pattern detected"]
    
    def export_signals(self, signals: List[CommoditySignal], output_path: str):
        """Export signals to JSON file"""
        data = [asdict(sig) for sig in signals]
        with open(output_path, 'w') as f:
            json.dump(data, f, indent=2)
        logger.info(f"Exported {len(signals)} signals to {output_path}")


# Example usage
if __name__ == "__main__":
    # TODO: Load data and run pipeline
    pass
