"""
Commodity AI Engine - Demand Leakage & Capture Opportunity Detection
INIBSA Smart Demand Signals Platform
"""

import argparse
import importlib.util
import json
import logging
from dataclasses import dataclass, asdict
from datetime import datetime, timedelta
from enum import Enum
from pathlib import Path
from typing import Dict, Iterable, List, Optional, Tuple

import numpy as np
import pandas as pd
from sklearn.cluster import KMeans
from sklearn.ensemble import RandomForestRegressor
from sklearn.preprocessing import StandardScaler

try:
    import lightgbm as lgb
except ImportError:  # pragma: no cover - fallback is validated at runtime
    lgb = None

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


class CustomerCluster(Enum):
    """Customer behavioral segments for commodity products"""
    LOYAL_HIGH_VOLUME = 0
    PROMISCUOUS_BUYERS = 1
    LOW_ENGAGEMENT = 2
    GROWING_ACCOUNTS = 3
    UNSTABLE_BEHAVIOR = 4


@dataclass
class CommoditySignal:
    """Signal generated by commodity engine for a specific customer/product"""
    customer_id: str
    product_family: str
    signal_type: str = "demand_leakage"
    leakage_score: float = 0.0
    predicted_monthly_consumption: float = 0.0
    observed_monthly_consumption: float = 0.0
    gap_units: float = 0.0
    estimated_lost_revenue: float = 0.0
    customer_cluster: str = ""
    urgency: float = 0.0
    confidence: float = 0.0
    recommended_action: str = ""
    timeline: List[str] = None
    
    def to_dict(self):
        """Convert to dictionary for JSON serialization"""
        data = asdict(self)
        return data


class CommodityCustomerCluster:
    """
    KMeans clustering for commodity product customers.
    Segments customers by purchasing behavior using precomputed feature tables.
    """

    _cluster_feature_columns: Tuple[str, ...] = (
        "customer_total_revenue",
        "customer_total_orders",
        "customer_avg_ticket",
        "customer_frequency",
        "days_since_last_order",
        "return_rate_30d",
        "campaign_lift",
        "coefficient_variation_30d",
    )
    _zero_fill_columns: Tuple[str, ...] = (
        "return_rate_30d",
        "campaign_lift",
    )
    _customer_id_columns: Tuple[str, ...] = (
        "client_id",
        "customer_id",
    )

    def __init__(self, n_clusters: int = 5, random_state: int = 42):
        self.n_clusters = n_clusters
        self.random_state = random_state
        self.kmeans = KMeans(n_clusters=n_clusters, random_state=random_state)
        self.scaler = StandardScaler()

    def load_inputs(self, features_dir: Path) -> pd.DataFrame:
        """Load client-level feature tables for clustering."""
        if not features_dir.exists():
            raise FileNotFoundError(f"Features directory not found: {features_dir}")

        client_path = features_dir / "client_features.parquet"
        if not client_path.exists():
            raise FileNotFoundError(f"Missing required file: {client_path}")

        logger.info("Loading client features from %s", client_path)
        df = pd.read_parquet(client_path)
        if df.empty:
            raise ValueError("client_features.parquet is empty")

        optional_path = features_dir / "client_product_features.parquet"
        if optional_path.exists():
            logger.info(
                "Optional client_product_features.parquet found at %s (not used for clustering)",
                optional_path,
            )

        logger.info("Loaded %s rows with %s columns", len(df), len(df.columns))
        return df

    def validate_schema(self, df: pd.DataFrame) -> None:
        """Validate the input schema against the Excel definition."""
        if df.empty:
            raise ValueError("Input features DataFrame is empty")

        schema_columns = self._load_schema_columns()
        missing_in_schema = sorted(set(self._cluster_feature_columns) - set(schema_columns))
        if missing_in_schema:
            missing = ", ".join(missing_in_schema)
            logger.error("Schema validation failed; missing in Excel schema: %s", missing)
            raise ValueError(f"Excel schema missing required clustering columns: {missing}")

        missing_in_df = sorted(set(self._cluster_feature_columns) - set(df.columns))
        if missing_in_df:
            missing = ", ".join(missing_in_df)
            logger.error("Schema validation failed; missing in input data: %s", missing)
            raise ValueError(f"Input data missing required clustering columns: {missing}")

        id_column = self._resolve_customer_id_column(df.columns)
        if id_column is None:
            logger.error("Schema validation failed; missing customer identifier column")
            raise ValueError("Input data must include client_id or customer_id")

        logger.info("Schema validation passed using identifier column %s", id_column)

    def prepare_matrix(self, df: pd.DataFrame) -> pd.DataFrame:
        """Prepare standardized numeric feature matrix for clustering."""
        self.validate_schema(df)
        features = self._coerce_and_fill(df.loc[:, self._cluster_feature_columns])

        if hasattr(self.scaler, "mean_"):
            scaled = self.scaler.transform(features)
            logger.info("Scaled features using existing scaler")
        else:
            scaled = self.scaler.fit_transform(features)
            logger.info("Fitted scaler and standardized features")

        return pd.DataFrame(scaled, columns=self._cluster_feature_columns, index=df.index)

    def fit(self, X: pd.DataFrame) -> None:
        """Fit KMeans clustering on a prepared feature matrix."""
        if X is None or len(X) == 0:
            raise ValueError("Cannot fit clustering on empty feature matrix")

        self.kmeans.fit(X)
        counts = np.bincount(self.kmeans.labels_, minlength=self.n_clusters)
        if (counts == 0).any():
            raise ValueError("At least one cluster has zero customers; adjust n_clusters")

        logger.info("Clustering fitted with %s clusters", self.n_clusters)

    def predict(self, X: pd.DataFrame) -> np.ndarray:
        """Predict cluster assignments for a prepared feature matrix."""
        if not hasattr(self.kmeans, "cluster_centers_"):
            raise ValueError("KMeans model is not fitted yet")
        return self.kmeans.predict(X)

    def build_cluster_profiles(self, raw_df: pd.DataFrame, labels: np.ndarray) -> pd.DataFrame:
        """Build mean profiles and counts for each cluster."""
        if raw_df.empty:
            raise ValueError("Cannot build profiles from empty data")

        self.validate_schema(raw_df)

        profiles_source = self._coerce_and_fill(raw_df.loc[:, self._cluster_feature_columns])
        profiles_source["cluster_id"] = labels

        means = profiles_source.groupby("cluster_id")[list(self._cluster_feature_columns)].mean()
        counts = profiles_source.groupby("cluster_id").size().rename("count")
        profiles = means.join(counts).reset_index()

        if (profiles["count"] == 0).any():
            raise ValueError("Cluster profiles contain empty clusters")

        logger.info("Built cluster profiles for %s clusters", len(profiles))
        return profiles

    def save_outputs(
        self,
        output_dir: Path,
        customer_ids: pd.Series,
        labels: np.ndarray,
        profiles: pd.DataFrame,
    ) -> None:
        """Persist cluster assignments and profiles to parquet files."""
        output_dir.mkdir(parents=True, exist_ok=True)
        assignments = pd.DataFrame(
            {
                "customer_id": customer_ids.astype("string"),
                "cluster_id": labels.astype(int),
            }
        )

        assignments_path = output_dir / "cluster_assignments.parquet"
        profiles_path = output_dir / "cluster_profiles.parquet"

        self._write_parquet(assignments, assignments_path)
        self._write_parquet(profiles, profiles_path)

        logger.info("Saved cluster assignments to %s", assignments_path)
        logger.info("Saved cluster profiles to %s", profiles_path)

    def get_cluster_name(self, cluster_id: int) -> str:
        """Get human-readable cluster name."""
        return CustomerCluster(cluster_id).name.lower()

    @staticmethod
    def _parquet_engine() -> str:
        if importlib.util.find_spec("pyarrow") is not None:
            return "pyarrow"
        if importlib.util.find_spec("fastparquet") is not None:
            return "fastparquet"
        raise RuntimeError(
            "Parquet output requires either 'pyarrow' or 'fastparquet' to be installed."
        )

    def _write_parquet(self, df: pd.DataFrame, output_path: Path) -> None:
        df.to_parquet(
            output_path,
            index=False,
            compression="snappy",
            engine=self._parquet_engine(),
        )

    @staticmethod
    def _schema_path() -> Path:
        return Path(__file__).resolve().parents[2] / "data_processing" / "inibsa_feature_tables.xlsx"

    def _load_schema_columns(self) -> List[str]:
        schema_path = self._schema_path()
        if not schema_path.exists():
            raise FileNotFoundError(f"Schema file not found: {schema_path}")

        try:
            schema_df = pd.read_excel(schema_path, sheet_name="clients")
        except ImportError as exc:
            raise ImportError(
                "Reading inibsa_feature_tables.xlsx requires 'openpyxl' to be installed"
            ) from exc
        except ValueError as exc:
            raise ValueError("Sheet 'clients' not found in schema workbook") from exc

        if "Column" not in schema_df.columns:
            raise ValueError("Schema sheet must include a 'Column' header")

        return (
            schema_df["Column"]
            .dropna()
            .astype(str)
            .str.strip()
            .tolist()
        )

    def _coerce_and_fill(self, features: pd.DataFrame) -> pd.DataFrame:
        filled = features.copy()
        for column in self._cluster_feature_columns:
            filled[column] = pd.to_numeric(filled[column], errors="coerce")

        for column in self._zero_fill_columns:
            filled[column] = filled[column].fillna(0)

        for column in self._cluster_feature_columns:
            if column in self._zero_fill_columns:
                continue
            median_value = filled[column].median()
            if pd.isna(median_value):
                median_value = 0
            filled[column] = filled[column].fillna(median_value)

        if filled.isna().any().any():
            logger.warning("Remaining NaNs found after filling; defaulting to 0")
            filled = filled.fillna(0)

        return filled

    def _resolve_customer_id_column(self, columns: Iterable[str]) -> Optional[str]:
        column_set = set(columns)
        for candidate in self._customer_id_columns:
            if candidate in column_set:
                return candidate
        return None


class DemandForecaster:
    """
    LightGBM-based demand forecasting for commodity products.
    Predicts expected monthly consumption.
    """

    _client_sheet = "clients"
    _product_sheet = "products"
    _client_product_sheet = "client_product_features"
    _required_feature_files: Tuple[str, ...] = (
        "client_product_features.parquet",
        "product_features.parquet",
        "client_features.parquet",
    )
    _cluster_file_name = "cluster_assignments.parquet"
    _target_candidates: Tuple[str, ...] = (
        "target_30d_sales",
        "next_30d_sales",
        "future_30d_sales",
        "expected_30d_sales",
        "rolling_sales_30d",
    )
    _time_columns: Tuple[str, ...] = (
        "snapshot_date",
        "feature_date",
        "as_of_date",
        "forecast_date",
        "date",
        "month",
    )
    _customer_id_candidates: Tuple[str, ...] = (
        "customer_id",
        "client_id",
    )
    _product_id_candidates: Tuple[str, ...] = (
        "product_id",
        "product_family",
        "family",
    )
    _priority_client_product_columns: Tuple[str, ...] = (
        "rolling_sales_30d",
        "sales_growth_30d",
        "days_since_last_product_order",
        "client_product_frequency",
        "client_product_avg_ticket",
        "client_product_return_rate",
        "campaign_lift_product",
        "client_product_total_revenue",
        "client_product_total_orders",
    )
    _priority_product_columns: Tuple[str, ...] = (
        "product_growth_30d",
        "product_frequency",
        "product_return_rate",
    )
    _priority_client_columns: Tuple[str, ...] = (
        "customer_frequency",
        "campaign_lift",
    )

    def __init__(self, model_params: Optional[Dict] = None):
        self.model = None
        self.model_backend = "lightgbm" if lgb is not None else "sklearn"
        self.feature_names: List[str] = []
        self.feature_dtypes: Dict[str, str] = {}
        self.categorical_levels: Dict[str, List[str]] = {}
        self.numeric_fill_values: Dict[str, float] = {}
        self.validation_rmse_: Optional[float] = None
        self.validation_mae_: Optional[float] = None
        self.base_confidence_: float = 0.5
        self.train_feature_means_: Optional[pd.Series] = None
        self.train_feature_stds_: Optional[pd.Series] = None
        self.training_order_: Optional[pd.Series] = None
        self.target_column: Optional[str] = None
        self.product_key_column: Optional[str] = None
        self.customer_key_column: str = "customer_id"
        self.model_params = model_params or {
            "learning_rate": 0.05,
            "num_leaves": 31,
            "max_depth": 5,
            "objective": "regression",
            "metric": "rmse",
            "verbosity": -1,
            "seed": 42,
        }

    def load_inputs(self, features_dir: Path, commodity_output_dir: Path) -> pd.DataFrame:
        """Load and merge feature tables with cluster assignments."""
        features_dir = Path(features_dir)
        commodity_output_dir = Path(commodity_output_dir)
        if not features_dir.exists():
            raise FileNotFoundError(f"Features directory not found: {features_dir}")
        if not commodity_output_dir.exists():
            raise FileNotFoundError(
                f"Commodity output directory not found: {commodity_output_dir}"
            )

        schema_contracts = self._load_schema_contracts()
        input_paths = {
            "client_product": features_dir / "client_product_features.parquet",
            "product": features_dir / "product_features.parquet",
            "client": features_dir / "client_features.parquet",
            "cluster": commodity_output_dir / self._cluster_file_name,
        }
        missing_files = [
            str(path) for path in input_paths.values() if not path.exists()
        ]
        if missing_files:
            raise FileNotFoundError(
                "Missing required forecast inputs: " + ", ".join(missing_files)
            )

        logger.info("Loading forecast inputs from %s", features_dir)
        client_product_df = self._canonicalize_client_product_df(
            pd.read_parquet(input_paths["client_product"])
        )
        product_df = self._canonicalize_product_df(pd.read_parquet(input_paths["product"]))
        client_df = self._canonicalize_client_df(pd.read_parquet(input_paths["client"]))
        cluster_df = self._canonicalize_cluster_df(pd.read_parquet(input_paths["cluster"]))

        self._validate_input_table(
            client_product_df,
            schema_contracts[self._client_product_sheet],
            "client_product_features.parquet",
            self._priority_client_product_columns,
            ("customer_id", self._resolved_product_key(client_product_df)),
        )
        self._validate_input_table(
            product_df,
            schema_contracts[self._product_sheet],
            "product_features.parquet",
            self._priority_product_columns,
            (self._resolved_product_key(product_df),),
        )
        self._validate_input_table(
            client_df,
            schema_contracts[self._client_sheet],
            "client_features.parquet",
            self._priority_client_columns,
            ("customer_id",),
        )
        self._validate_cluster_assignments(cluster_df)

        merged = client_product_df.merge(
            client_df,
            how="left",
            on="customer_id",
            suffixes=("", "_client"),
            validate="many_to_one",
        )
        product_key = self._resolved_product_key(client_product_df)
        merged = merged.merge(
            product_df,
            how="left",
            on=product_key,
            suffixes=("", "_product"),
            validate="many_to_one",
        )
        merged = merged.merge(
            cluster_df[["customer_id", "cluster_id"]],
            how="left",
            on="customer_id",
            validate="many_to_one",
        )

        self.product_key_column = product_key
        self.validate_schema(merged)
        logger.info("Merged forecast frame with shape %s", merged.shape)
        return merged

    def validate_schema(self, df: pd.DataFrame) -> None:
        """Validate merged forecast schema before training."""
        if df.empty:
            raise ValueError("Forecast input DataFrame is empty")

        required_columns = {
            "customer_id",
            "cluster_id",
            self._resolved_product_key(df),
        }
        for column_group in (
            self._priority_client_product_columns,
            self._priority_product_columns,
            self._priority_client_columns,
        ):
            required_columns.update(column_group)

        missing_columns = sorted(column for column in required_columns if column not in df.columns)
        if missing_columns:
            raise ValueError(
                "Merged forecast frame is missing required columns: "
                + ", ".join(missing_columns)
            )

        for column in self._target_candidates:
            if column in df.columns:
                self.target_column = column
                break
        if self.target_column is None:
            raise ValueError(
                "Forecast target column not found. Expected one of: "
                + ", ".join(self._target_candidates)
            )
        logger.info("Using %s as forecast target column", self.target_column)

    def build_training_frame(self, df: pd.DataFrame) -> Tuple[pd.DataFrame, pd.Series]:
        """Prepare the model feature matrix and supervised target."""
        self.validate_schema(df)

        target = pd.to_numeric(df[self.target_column], errors="coerce")
        if target.isna().all():
            raise ValueError(f"Target column {self.target_column} contains only NaN values")

        excluded_columns = {
            "customer_id",
            "cluster_id",
            self.target_column,
            "predicted_30d_sales",
            "forecast_confidence",
        }
        product_key = self._resolved_product_key(df)
        if product_key == "product_id" and "product_family" in df.columns:
            excluded_columns.discard("product_family")
        if product_key == "product_family":
            excluded_columns.discard("product_family")

        feature_columns = [
            column
            for column in df.columns
            if column not in excluded_columns and not column.endswith("_id")
        ]
        feature_columns.append("cluster_id")
        feature_columns = list(dict.fromkeys(feature_columns))

        missing_for_training = [
            column for column in feature_columns if column not in df.columns
        ]
        if missing_for_training:
            raise ValueError(
                "Missing expected training columns: " + ", ".join(missing_for_training)
            )

        model_df = df.loc[:, feature_columns].copy()
        valid_mask = target.notna()
        model_df = model_df.loc[valid_mask].reset_index(drop=True)
        target = target.loc[valid_mask].clip(lower=0).reset_index(drop=True)

        self.training_order_ = self._build_time_order(model_df)
        X = self._prepare_model_frame(model_df, fit=True)
        self.feature_names = X.columns.tolist()
        logger.info("Built training matrix with shape %s", X.shape)
        return X, target

    def train(self, X: pd.DataFrame, y: pd.Series) -> None:
        """Train the demand forecasting model using a time-aware split."""
        if X.empty or y.empty:
            raise ValueError("Cannot train forecast model on empty data")

        if self.training_order_ is not None and len(self.training_order_) == len(X):
            order = self.training_order_
        else:
            order = self._build_time_order(X)
        train_idx, val_idx = self._time_aware_split_indices(order, len(X))

        X_train = X.iloc[train_idx].reset_index(drop=True)
        y_train = y.iloc[train_idx].reset_index(drop=True)
        X_val = X.iloc[val_idx].reset_index(drop=True)
        y_val = y.iloc[val_idx].reset_index(drop=True)

        self.train_feature_means_ = X_train.mean()
        self.train_feature_stds_ = X_train.std(ddof=0).replace(0, 1).fillna(1)

        if self.model_backend == "lightgbm":
            train_data = lgb.Dataset(X_train, label=y_train, feature_name=self.feature_names)
            valid_sets = [train_data]
            valid_names = ["train"]
            callbacks = []
            if not X_val.empty:
                valid_data = lgb.Dataset(
                    X_val,
                    label=y_val,
                    feature_name=self.feature_names,
                    reference=train_data,
                )
                valid_sets.append(valid_data)
                valid_names.append("valid")
                callbacks.append(lgb.early_stopping(20, verbose=False))

            self.model = lgb.train(
                self.model_params,
                train_data,
                num_boost_round=200,
                valid_sets=valid_sets,
                valid_names=valid_names,
                callbacks=callbacks,
            )
        else:
            fallback_params = {
                "n_estimators": 300,
                "max_depth": 8,
                "min_samples_leaf": 2,
                "random_state": 42,
                "n_jobs": -1,
            }
            self.model = RandomForestRegressor(**fallback_params)
            self.model.fit(X_train, y_train)

        eval_features = X_val if not X_val.empty else X_train
        eval_target = y_val if not y_val.empty else y_train
        eval_pred = np.clip(self.predict(eval_features), a_min=0, a_max=None)
        residuals = eval_target.to_numpy(dtype=float) - eval_pred
        self.validation_rmse_ = float(np.sqrt(np.mean(np.square(residuals))))
        self.validation_mae_ = float(np.mean(np.abs(residuals)))
        denominator = float(np.mean(np.abs(eval_target.to_numpy(dtype=float)))) + 1e-6
        relative_error = min(self.validation_mae_ / denominator, 1.0)
        self.base_confidence_ = float(np.clip(1.0 - relative_error, 0.05, 0.95))
        logger.info(
            "Demand forecaster trained using %s backend; validation RMSE=%.4f, base confidence=%.3f",
            self.model_backend,
            self.validation_rmse_,
            self.base_confidence_,
        )

    def predict(self, X: pd.DataFrame) -> np.ndarray:
        """Predict expected consumption."""
        if self.model is None:
            raise ValueError("Model not trained yet")
        transformed = self._prepare_model_frame(X, fit=False)
        predictions = self.model.predict(transformed)
        return np.clip(np.asarray(predictions, dtype=float), a_min=0, a_max=None)

    def estimate_confidence(self, X: pd.DataFrame, y_pred: np.ndarray) -> np.ndarray:
        """Estimate per-row forecast confidence in the [0, 1] range."""
        if self.train_feature_means_ is None or self.train_feature_stds_ is None:
            raise ValueError("Forecast model must be trained before estimating confidence")

        transformed = self._prepare_model_frame(X, fit=False)
        aligned_means = self.train_feature_means_.reindex(transformed.columns).fillna(0)
        aligned_stds = self.train_feature_stds_.reindex(transformed.columns).fillna(1)
        z_scores = ((transformed - aligned_means) / aligned_stds).abs().replace([np.inf, -np.inf], 0)
        drift_penalty = np.tanh(z_scores.mean(axis=1) / 3.0)

        scale = (
            self.validation_rmse_
            if self.validation_rmse_ is not None and self.validation_rmse_ > 0
            else max(float(np.nanmean(np.abs(y_pred))), 1.0)
        )
        uncertainty = np.clip(np.abs(y_pred) / (np.abs(y_pred) + scale), 0, 1)
        confidence = self.base_confidence_ * (1 - 0.5 * drift_penalty) * (0.6 + 0.4 * uncertainty)
        confidence = np.nan_to_num(confidence.to_numpy(dtype=float), nan=self.base_confidence_)
        return np.clip(confidence, 0, 1)

    def save_outputs(
        self,
        output_dir: Path,
        base_df: pd.DataFrame,
        y_pred: np.ndarray,
        confidence: np.ndarray,
    ) -> None:
        """Persist the consumption forecast parquet output."""
        output_dir = Path(output_dir)
        output_dir.mkdir(parents=True, exist_ok=True)

        product_key = self._resolved_product_key(base_df)
        export_df = pd.DataFrame(
            {
                "customer_id": base_df["customer_id"].astype("string"),
                product_key: base_df[product_key].astype("string"),
                "predicted_30d_sales": np.clip(np.asarray(y_pred, dtype=float), 0, None),
                "forecast_confidence": np.clip(np.asarray(confidence, dtype=float), 0, 1),
                "forecast_date": self._build_forecast_dates(base_df),
            }
        )

        if export_df.isna().any().any():
            missing_columns = export_df.columns[export_df.isna().any()].tolist()
            raise ValueError(
                "Forecast output contains NaN values in columns: " + ", ".join(missing_columns)
            )

        output_path = output_dir / "consumption_forecast.parquet"
        export_df.to_parquet(
            output_path,
            index=False,
            compression="snappy",
            engine=CommodityCustomerCluster._parquet_engine(),
        )
        logger.info("Saved consumption forecast to %s", output_path)

    def prepare_features(
        self,
        sales_df: pd.DataFrame,
        clustering_results: Optional[pd.DataFrame] = None,
        clients_df: Optional[pd.DataFrame] = None,
    ) -> Tuple[pd.DataFrame, pd.Series]:
        """
        Backward-compatible wrapper around build_training_frame.

        This component now expects a merged feature frame instead of raw sales tables.
        """
        if isinstance(sales_df, pd.DataFrame) and "rolling_sales_30d" in sales_df.columns:
            return self.build_training_frame(sales_df)
        raise ValueError(
            "DemandForecaster.prepare_features now expects the merged feature frame returned "
            "by load_inputs(). Raw sales DataFrames are not supported in this component."
        )

    def get_feature_importance(self) -> Dict[str, float]:
        """Get feature importance from the active forecasting backend."""
        if self.model is None:
            return {}
        if self.model_backend == "lightgbm":
            importance = self.model.feature_importance()
        else:
            importance = getattr(self.model, "feature_importances_", np.zeros(len(self.feature_names)))
        return {name: float(imp) for name, imp in zip(self.feature_names, importance)}

    @staticmethod
    def _schema_path() -> Path:
        return Path(__file__).resolve().parents[2] / "data_processing" / "inibsa_feature_tables.xlsx"

    def _load_schema_contracts(self) -> Dict[str, List[str]]:
        schema_path = self._schema_path()
        if not schema_path.exists():
            raise FileNotFoundError(f"Schema file not found: {schema_path}")

        try:
            workbook = pd.ExcelFile(schema_path)
        except ImportError as exc:
            raise ImportError(
                "Reading inibsa_feature_tables.xlsx requires 'openpyxl' to be installed"
            ) from exc

        contracts = {}
        for sheet_name in (
            self._client_sheet,
            self._product_sheet,
            self._client_product_sheet,
        ):
            if sheet_name not in workbook.sheet_names:
                raise ValueError(f"Sheet '{sheet_name}' not found in schema workbook")
            sheet_df = pd.read_excel(schema_path, sheet_name=sheet_name)
            if "Column" not in sheet_df.columns:
                raise ValueError(f"Schema sheet '{sheet_name}' must include a 'Column' header")
            contracts[sheet_name] = (
                sheet_df["Column"].dropna().astype(str).str.strip().tolist()
            )
        return contracts

    def _validate_input_table(
        self,
        df: pd.DataFrame,
        schema_columns: List[str],
        file_name: str,
        priority_columns: Iterable[str],
        identifier_columns: Iterable[str],
    ) -> None:
        if df.empty:
            raise ValueError(f"{file_name} is empty")

        required_columns = self._normalize_expected_columns(schema_columns)
        required_columns.update(priority_columns)
        required_columns.update(identifier_columns)
        missing_columns = sorted(column for column in required_columns if column not in df.columns)
        if missing_columns:
            raise ValueError(
                f"{file_name} is missing required columns from Excel contract: "
                + ", ".join(missing_columns)
            )
        logger.info("Validated %s against Excel schema", file_name)

    def _validate_cluster_assignments(self, df: pd.DataFrame) -> None:
        required_columns = {"customer_id", "cluster_id"}
        missing_columns = sorted(required_columns - set(df.columns))
        if missing_columns:
            raise ValueError(
                "cluster_assignments.parquet is missing required columns: "
                + ", ".join(missing_columns)
            )
        if df["cluster_id"].isna().any():
            raise ValueError("cluster_assignments.parquet contains NaN cluster_id values")

    def _canonicalize_client_product_df(self, df: pd.DataFrame) -> pd.DataFrame:
        renamed = df.copy()
        customer_column = self._find_first_column(renamed.columns, self._customer_id_candidates)
        if customer_column is None:
            raise ValueError("client_product_features.parquet must include client_id or customer_id")
        renamed = renamed.rename(columns={customer_column: "customer_id"})

        if "family" in renamed.columns and "product_family" not in renamed.columns:
            renamed = renamed.rename(columns={"family": "product_family"})
        if "client_product_total_orders" not in renamed.columns:
            total_orders_candidates = (
                "client_product_total_units",
                "client_product_orders",
                "client_product_total_transactions",
            )
            fallback = self._find_first_column(renamed.columns, total_orders_candidates)
            if fallback is not None:
                renamed = renamed.rename(columns={fallback: "client_product_total_orders"})
        return renamed

    def _canonicalize_product_df(self, df: pd.DataFrame) -> pd.DataFrame:
        renamed = df.copy()
        if "family" in renamed.columns and "product_family" not in renamed.columns:
            renamed = renamed.rename(columns={"family": "product_family"})
        return renamed

    def _canonicalize_client_df(self, df: pd.DataFrame) -> pd.DataFrame:
        renamed = df.copy()
        customer_column = self._find_first_column(renamed.columns, self._customer_id_candidates)
        if customer_column is None:
            raise ValueError("client_features.parquet must include client_id or customer_id")
        return renamed.rename(columns={customer_column: "customer_id"})

    def _canonicalize_cluster_df(self, df: pd.DataFrame) -> pd.DataFrame:
        renamed = df.copy()
        customer_column = self._find_first_column(renamed.columns, self._customer_id_candidates)
        if customer_column is None:
            raise ValueError("cluster_assignments.parquet must include client_id or customer_id")
        return renamed.rename(columns={customer_column: "customer_id"})

    @staticmethod
    def _normalize_expected_columns(columns: Iterable[str]) -> set[str]:
        normalized = set()
        for column in columns:
            if column == "client_id":
                normalized.add("customer_id")
            elif column == "family":
                normalized.add("product_family")
            else:
                normalized.add(column)
        return normalized

    @staticmethod
    def _find_first_column(columns: Iterable[str], candidates: Iterable[str]) -> Optional[str]:
        column_set = set(columns)
        for candidate in candidates:
            if candidate in column_set:
                return candidate
        return None

    def _resolved_product_key(self, df: pd.DataFrame) -> str:
        product_key = self._find_first_column(df.columns, self._product_id_candidates)
        if product_key is None:
            raise ValueError("Forecast inputs must include product_id or product_family/family")
        return product_key

    def _prepare_model_frame(self, df: pd.DataFrame, fit: bool) -> pd.DataFrame:
        frame = df.copy()
        transformed_columns = {}

        for column in frame.columns:
            if fit:
                inferred_numeric = pd.to_numeric(frame[column], errors="coerce")
                numeric_ratio = inferred_numeric.notna().mean()
                if numeric_ratio >= 0.8:
                    fill_value = inferred_numeric.median()
                    if pd.isna(fill_value):
                        fill_value = 0.0
                    self.feature_dtypes[column] = "numeric"
                    self.numeric_fill_values[column] = float(fill_value)
                    transformed_columns[column] = inferred_numeric.fillna(fill_value).astype(float)
                else:
                    values = frame[column].astype("string").fillna("__missing__")
                    categories = pd.Index(values.unique()).astype(str).tolist()
                    self.feature_dtypes[column] = "categorical"
                    self.categorical_levels[column] = categories
                    codes = pd.Categorical(values, categories=categories).codes.astype(float)
                    transformed_columns[column] = pd.Series(codes, index=frame.index)
            else:
                dtype = self.feature_dtypes.get(column)
                if dtype == "numeric":
                    numeric_series = pd.to_numeric(frame[column], errors="coerce")
                    fill_value = self.numeric_fill_values.get(column, 0.0)
                    transformed_columns[column] = numeric_series.fillna(fill_value).astype(float)
                elif dtype == "categorical":
                    categories = self.categorical_levels.get(column, [])
                    values = frame[column].astype("string").fillna("__missing__")
                    codes = pd.Categorical(values, categories=categories).codes.astype(float)
                    transformed_columns[column] = pd.Series(codes, index=frame.index)
                else:
                    transformed_columns[column] = pd.Series(0.0, index=frame.index)

        transformed = pd.DataFrame(transformed_columns, index=frame.index)
        transformed = transformed.replace([np.inf, -np.inf], np.nan).fillna(0.0)
        if not fit:
            for missing_column in self.feature_names:
                if missing_column not in transformed.columns:
                    transformed[missing_column] = 0.0
            transformed = transformed.loc[:, self.feature_names]
        return transformed

    def _build_time_order(self, X: pd.DataFrame) -> pd.Series:
        for column in self._time_columns:
            if column not in X.columns:
                continue
            series = X[column]
            if column == "month":
                parsed = pd.to_numeric(series, errors="coerce")
            else:
                parsed = pd.to_datetime(series, errors="coerce")
                if parsed.notna().sum() > 0:
                    logger.info("Using %s for time-aware forecast split", column)
                    numeric_order = parsed.map(
                        lambda value: value.value if pd.notna(value) else np.nan
                    )
                    numeric_order = numeric_order.fillna(numeric_order.median()).fillna(0)
                    return pd.Series(numeric_order, index=X.index)
            if parsed.notna().sum() > 0:
                logger.info("Using %s for time-aware forecast split", column)
                return pd.Series(parsed, index=X.index)

        if "days_since_last_product_order" in X.columns:
            fallback = pd.to_numeric(X["days_since_last_product_order"], errors="coerce").fillna(0)
            logger.info(
                "No explicit timestamp found; using days_since_last_product_order as recency proxy"
            )
            return fallback * -1

        logger.warning("No time column found; using row order for deterministic split")
        return pd.Series(np.arange(len(X)), index=X.index)

    @staticmethod
    def _time_aware_split_indices(order: pd.Series, total_rows: int) -> Tuple[np.ndarray, np.ndarray]:
        if total_rows < 2:
            single_index = np.arange(total_rows)
            return single_index, single_index

        ordered_index = order.sort_values(kind="mergesort").index.to_numpy()
        split_point = max(int(total_rows * 0.8), 1)
        split_point = min(split_point, total_rows - 1)
        train_idx = ordered_index[:split_point]
        val_idx = ordered_index[split_point:]
        return train_idx, val_idx

    def _build_forecast_dates(self, base_df: pd.DataFrame) -> pd.Series:
        for column in self._time_columns:
            if column not in base_df.columns:
                continue
            parsed = pd.to_datetime(base_df[column], errors="coerce")
            if parsed.notna().sum() == 0:
                continue
            return (parsed + pd.Timedelta(days=30)).dt.date.astype("string")

        fallback_date = pd.Timestamp.utcnow().date().isoformat()
        return pd.Series([fallback_date] * len(base_df), index=base_df.index, dtype="string")


class DemandLeakageDetector:
    """
    Detects demand leakage (expected > observed) indicating potential competitor capture.
    """
    
    def __init__(self, min_confidence_threshold: float = 0.5):
        self.min_confidence_threshold = min_confidence_threshold
        
    def compute_leakage(self, 
                       predicted_consumption: pd.Series,
                       observed_consumption: pd.Series,
                       customer_volatility: pd.Series,
                       model_confidence: float = 0.85) -> pd.DataFrame:
        """
        Compute demand leakage for customers.
        
        Formula:
            base_gap = (predicted - observed) / predicted
            leakage_score = base_gap × volatility_factor × confidence
        
        Args:
            predicted_consumption: Expected monthly consumption
            observed_consumption: Actual monthly consumption
            customer_volatility: Historical variance in purchases
            model_confidence: Confidence in forecasting model
            
        Returns:
            DataFrame with leakage metrics
        """
        results = pd.DataFrame({
            'predicted': predicted_consumption,
            'observed': observed_consumption
        })
        
        # Avoid division by zero
        results['base_gap'] = np.where(
            results['predicted'] > 0,
            (results['predicted'] - results['observed']) / results['predicted'],
            0
        )
        
        # Normalize by customer volatility and model confidence
        results['leakage_score'] = (
            np.maximum(results['base_gap'], 0)  # Only positive gaps
            * customer_volatility.fillna(1.0)   # Account for variance
            * model_confidence
        )
        
        # Clip to 0-1 range
        results['leakage_score'] = results['leakage_score'].clip(0, 1)
        
        return results
    
    def filter_significant_leakage(self, leakage_df: pd.DataFrame, 
                                   min_gap_units: int = 10) -> pd.DataFrame:
        """Filter to significant leakage events only"""
        return leakage_df[
            (leakage_df['leakage_score'] > self.min_confidence_threshold) &
            ((leakage_df['predicted'] - leakage_df['observed']) >= min_gap_units)
        ]


class CaptureScoringEngine:
    """
    Scores and ranks capture opportunities.
    Combines leakage data with business metrics to prioritize sales actions.
    """
    
    def __init__(self):
        self.weights = {
            'leakage': 0.40,
            'customer_value': 0.30,
            'urgency': 0.20,
            'confidence': 0.10
        }
        
    def compute_customer_value(self, customer_id: str, clients_df: pd.DataFrame,
                              historical_spend: pd.Series) -> float:
        """Normalize customer value to 0-1 scale"""
        # TODO: Implement based on spend, tier, clinic size
        # Should return normalized score 0-1
        pass
    
    def compute_urgency(self, leakage_df: pd.DataFrame) -> float:
        """
        Compute urgency based on:
        - Magnitude of leakage
        - Trend (increasing vs stable)
        - Days since alert
        """
        # TODO: Implement urgency scoring
        # Larger leakage = more urgent
        # Increasing trend = more urgent
        pass
    
    def score_opportunities(self, leakage_df: pd.DataFrame,
                           customers_df: pd.DataFrame,
                           historical_spend: pd.Series,
                           forecaster: DemandForecaster) -> pd.DataFrame:
        """
        Compute overall capture opportunity score.
        
        Formula:
            score = (leakage × 0.40) + (value × 0.30) + (urgency × 0.20) + (confidence × 0.10)
        
        Returns:
            DataFrame with scores ranked by opportunity
        """
        scored = leakage_df.copy()
        
        # Normalize components
        scored['leakage_norm'] = leakage_df['leakage_score']
        scored['value_norm'] = leakage_df.index.map(
            lambda x: self.compute_customer_value(x, customers_df, historical_spend)
        )
        scored['urgency_norm'] = leakage_df.index.map(
            lambda x: self.compute_urgency(leakage_df.loc[[x]])
        )
        scored['confidence_norm'] = 0.85  # From forecaster
        
        # Weighted score
        scored['capture_score'] = (
            scored['leakage_norm'] * self.weights['leakage'] +
            scored['value_norm'] * self.weights['customer_value'] +
            scored['urgency_norm'] * self.weights['urgency'] +
            scored['confidence_norm'] * self.weights['confidence']
        ) * 100
        
        # Rank by score
        scored = scored.sort_values('capture_score', ascending=False)
        scored['priority_rank'] = range(1, len(scored) + 1)
        
        return scored
    
    def generate_action_recommendations(self, scored_df: pd.DataFrame) -> Dict[str, str]:
        """Generate human-readable recommended actions for sales team"""
        actions = {}
        for idx, row in scored_df.iterrows():
            if row['capture_score'] > 80:
                action = "URGENT: High-value competitor capture - sales call within 24h"
            elif row['capture_score'] > 60:
                action = "HIGH: Significant demand gap - schedule follow-up call"
            elif row['capture_score'] > 40:
                action = "MEDIUM: Monitor for competitive activity"
            else:
                action = "LOW: Watch for changes in pattern"
            actions[idx] = action
        return actions


class CommoditySignalGenerator:
    """
    Orchestrates the complete commodity engine pipeline.
    Combines all components to generate actionable signals.
    """
    
    def __init__(self, sales_df: pd.DataFrame, clients_df: pd.DataFrame, 
                products_df: pd.DataFrame):
        self.sales_df = sales_df
        self.clients_df = clients_df
        self.products_df = products_df
        
        self.clusterer = CommodityCustomerCluster()
        self.forecaster = DemandForecaster()
        self.leakage_detector = DemandLeakageDetector()
        self.scorer = CaptureScoringEngine()
        
    def generate_signals(self) -> List[CommoditySignal]:
        """
        Run complete pipeline and generate signals.
        
        Steps:
        1. Cluster customers
        2. Forecast demand
        3. Detect leakage
        4. Score opportunities
        5. Generate explanations
        
        Returns:
            List of CommoditySignal objects
        """
        logger.info("Starting commodity engine pipeline...")
        
        # Step 1: Clustering
        logger.info("Step 1: Clustering customers...")
        cluster_features = self.clusterer.prepare_features(self.sales_df, self.clients_df)
        self.clusterer.fit(cluster_features)
        cluster_assignments = self.clusterer.predict(cluster_features)
        
        # Step 2: Forecasting
        logger.info("Step 2: Forecasting demand...")
        forecast_features, forecast_target = self.forecaster.prepare_features(
            self.sales_df, cluster_assignments, self.clients_df
        )
        self.forecaster.train(forecast_features, forecast_target)
        predictions = self.forecaster.predict(forecast_features)
        
        # Step 3: Leakage detection
        logger.info("Step 3: Detecting demand leakage...")
        observed = self._get_observed_consumption()
        leakage_results = self.leakage_detector.compute_leakage(
            pd.Series(predictions),
            observed
        )
        
        # Step 4: Scoring
        logger.info("Step 4: Scoring opportunities...")
        scored = self.scorer.score_opportunities(
            leakage_results, self.clients_df, observed, self.forecaster
        )
        actions = self.scorer.generate_action_recommendations(scored)
        
        # Step 5: Generate signals
        logger.info("Step 5: Generating signals...")
        signals = self._create_signals(scored, actions)
        
        logger.info(f"Generated {len(signals)} signals")
        return signals
    
    def _get_observed_consumption(self) -> pd.Series:
        """Extract observed consumption from sales data"""
        # TODO: Implement - group sales by customer/period
        pass
    
    def _create_signals(self, scored_df: pd.DataFrame, actions: Dict[str, str]) -> List[CommoditySignal]:
        """Create CommoditySignal objects from scored data"""
        signals = []
        for customer_id, row in scored_df.iterrows():
            signal = CommoditySignal(
                customer_id=str(customer_id),
                product_family=row.get('product_family', 'Unknown'),
                signal_type='demand_leakage',
                leakage_score=float(row['leakage_score']),
                predicted_monthly_consumption=float(row['predicted']),
                observed_monthly_consumption=float(row['observed']),
                gap_units=float(row['predicted'] - row['observed']),
                estimated_lost_revenue=float((row['predicted'] - row['observed']) * 8),  # Avg price
                customer_cluster=row.get('cluster', 'Unknown'),
                urgency=float(row['urgency_norm']),
                confidence=0.85,
                recommended_action=actions.get(customer_id, ""),
                timeline=self._build_timeline(customer_id)
            )
            signals.append(signal)
        return signals
    
    def _build_timeline(self, customer_id: str) -> List[str]:
        """Build timeline of customer behavior"""
        # TODO: Implement timeline reconstruction from historical data
        return ["Pattern detected"]
    
    def export_signals(self, signals: List[CommoditySignal], output_path: str):
        """Export signals to JSON file"""
        data = [asdict(sig) for sig in signals]
        with open(output_path, 'w') as f:
            json.dump(data, f, indent=2)
        logger.info(f"Exported {len(signals)} signals to {output_path}")


def run_consumption_forecast(mode: str, project_root: Optional[Path] = None) -> Path:
    """Run the consumption forecast component for a given mode."""
    project_root = (
        Path(project_root).resolve()
        if project_root is not None
        else Path(__file__).resolve().parents[3]
    )
    features_dir = project_root / "backend" / "processed_data" / mode / "features"
    commodity_output_dir = project_root / "backend" / "commodity-ai-engine" / "output" / mode

    forecaster = DemandForecaster()
    merged_df = forecaster.load_inputs(features_dir, commodity_output_dir)
    X, y = forecaster.build_training_frame(merged_df)
    forecaster.train(X, y)

    prediction_frame = merged_df.reset_index(drop=True)
    y_pred = forecaster.predict(prediction_frame.loc[:, forecaster.feature_names])
    confidence = forecaster.estimate_confidence(
        prediction_frame.loc[:, forecaster.feature_names],
        y_pred,
    )
    forecaster.save_outputs(commodity_output_dir, prediction_frame, y_pred, confidence)
    return commodity_output_dir / "consumption_forecast.parquet"


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Run the commodity consumption forecast")
    parser.add_argument(
        "--mode",
        default="historical",
        choices=("historical", "daily"),
        help="Input/output mode for the forecast pipeline",
    )
    args = parser.parse_args()
    output_path = run_consumption_forecast(args.mode)
    logger.info("Consumption forecast completed: %s", output_path)
